### PR TITLE
fix(ci): Install webkit2gtk on ubuntu when building smoke tests via prod

### PR DESCRIPTION
**Pull request by rajivshah3**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
The `via-prod` jobs are silently failing on Ubuntu (somehow, GitHub Actions thinks that the job passed even though it [failed](https://github.com/tauri-apps/tauri/pull/187/checks?check_run_id=357905199#step:11:107)) because `webkit2gtk` isn't installed

### CODE REVIEW

**Comment by nothingismagick** [comment]
Any idea why that one test is failing? Should we rerun it?

**Comment by rajivshah3** [comment]
I’m not entirely sure what happened there. Maybe a rerun will do the trick?

**Comment by nothingismagick** [comment]
I reran it - and it passed - maybe it bailed because another pipeline finished while it was running

**Comment by jbolda** [comment]
How was this passing prior to this change? 😕

**Comment by nothingismagick** [comment]
because we never actually STARTED the app

**Comment by rajivshah3** [comment]
> How was this passing prior to this change? 😕

It seems like Yarn wasn’t picking up the exit code from Cargo as an actual failure, so the job just continued

**Comment by jbolda** [comment]
Oh wow, we should make a note to come back and make sure that actually fails properly. Good catch 👍

**Pull request merged**
