### PR TITLE
chore(deps): js updates

### PR DESCRIPTION
**Pull request by nothingismagick**
**What kind of change does this PR introduce?** (check at least one)

- [x] Other, please describe:

Deps Update

### CODE REVIEW

**Comment by lucasfernog** [comment]
Can you also pls fix the eslint issue? It's bugging me :D

**Comment by nothingismagick** [comment]
> Can you also pls fix the eslint issue? It's bugging me :D

of course

**Comment by lucasfernog** [comment]
Also the audit is failing, we need to patch it.

**Comment by nothingismagick** [comment]
So @lucasfernog  - this is ready for review and merging (unless we want to wait for @jbolda to find the fix for CTA)

**Review by jbolda — APPROVED** [review]
Looks good to me. I think we can address the test fail in a separate PR.

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
