### PR TITLE
fix(bundler/macos): clean up .app bundle if only .dmg is enabled #7081

### LINKED ISSUE #7081: [bug] bundler doesn't clean up `.app` bundle if only `.dmg` is enabled
> This issue has been upstreamed from https://github.com/tauri-apps/tauri-action/issues/476 

Is it possible to consider adding a variable **Bundles** like **pnpm tauri build  --help**

Sometimes I only want to upload MSI and DMG bundles, but currently it will upload all the bundles, include app and exe.

```
  -b, --bundles [<BUNDLES>...]
          Space or comma separated list of bundles to package.
          
          Each bundle must be one of `deb`, `appimage`, `msi`, `app` or `dmg` on MacOS and `updater` on all platforms. If `none` is specified, the bundler will be skipped.
          
          Note that the `updater` bundle is not automatically added so you must specify it if the updater is enabled.
```

### PR DESCRIPTION
**Pull request by fcfangcc**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

fix #7081. clean up .app bundle if only .dmg is enabled

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks for contributing! ❤️ 

2 things:
1) We require all commits to be signed across Tauri's repositories. Follow [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) to set up commit signing. Once **all** the commits in this PR are signed we can merge your contribution. Thanks for being part of our community!
2) I _think_ we also need to check if the Updater bundle is being build (which will happen _after_ the .dmg bundle is being build) so that it doesn't have to rebuild&resign the .app bundle. -> The "after the .dmg bundle" thing is important because that means we can't just extend the existing `package_type == MacOsBundle` check, you could reset the vec in a separate check or something idk

**Comment by fcfangcc** [comment]
Only in the **platform::xx::bundle_project**  method can get tmp files.
My idea is  change **platform::xx::bundle_project** method return  like 
```rust
pub struct BuildBundle {
  bundles: Vec<PathBuf>,
  trashes: Vec<PathBuf>,
}
// pub fn bundle_project(settings: &Settings) -> crate::Result<Vec<PathBuf>>
pub fn bundle_project(settings: &Settings) -> crate::Result<BuildBundle> {
...
}
```

Then in **bundle::bundle_project** like 

```rust

let trashes = vec![]
for package_type in &package_types {
  let bundle = match package_type {
    #[cfg(target_os = "macos")]
    PackageType::MacOsBundle => macos::app::bundle_project(&settings)?,
    #[cfg(target_os = "macos")]
    PackageType::IosBundle => macos::ios::bundle_project(&settings)?,
    // dmg is dependant of MacOsBundle, we send our bundles to prevent rebuilding
    ...
    _ => {
      warn!("ignoring {:?}", package_type);
      continue;
    }
  };

  trashes.extend_from_slice(&bundle.trashes)
}
// clean up trashes after all bundle is build.
```

@FabianLars If it's suitable, I will implement it 😃

**Comment by FabianLars** [comment]
Changing function signatures is a bit tricky because it's technically a breaking chance the the bundler is also released as a normal crate 🤔 

Does my idea not work? To be clear, what i meant is to add something like this right above the `for app_bundle_path in app_bundle_paths {}` line
```rs
if !bundles
    .iter()
    .filter(|bundle| bundle.package_type == PackageType::Updater) {
      app_bundle_paths.clear();
    }
```

**Comment by fcfangcc** [comment]
emm...
I misunderstand your meaning

**Review by lucasfernog — DISMISSED** [review]

**Comment by FabianLars** [comment]
Just in case: It's missing a changefile

**Comment by lucasfernog** [comment]
Totally missed it, nice catch :)

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
