### PR TITLE
fix(core/tauri): upgrade `open` to 3.2 to fix a bug on Windows

### LINKED ISSUE #6438: [bug]  After the project is packaged, the cmd window displays when executing the shell.open(url) method.
### Describe the bug

After the project is packaged, the cmd window displays when executing the shell.open(url) method. And there is no problem in the development environment.

Screenshots
bugs

### Reproduction

1. create a new project, and modify "greet" method
```tsx
async function greet() {
    open("https://www.baidu.com")
    setGreetMsg(await invoke("greet", { name }));
}
```
2. yarn tauri build

### Expected behavior

The cmd window should not appear

### Platform and versions

```text
› OS: Windows 10.0.19044 X64
  › Webview2: 110.0.1587.69
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

### Stack trace

_No response_

### Additional context

_No response_

### LINKED ISSUE #6473: [bug] Shell API open command opens trunctated URL on Windows if URL contains ampersand
### Describe the bug

When using the `open` command of the Shell API to open a URL in the default browser and the URL contains multiple query params joined by `&`, the browser instead opens a truncated URL that only comprises the characters up to the first ampersand. 

### Reproduction

Trying to open `https://tauri.app/?a=1&b=2` in the default browser via

```ts
import { open } from '@tauri-apps/api/shell';
await open('https://tauri.app/?a=1&b=2');
```

opens `https://tauri.app/?a=1` instead.

### Expected behavior

I would expect that the original URL `https://tauri.app/?a=1&b=2` is opened.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 110.0.1587.69
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Build Tools 2022
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.66.0
  › cargo: 1.66.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:5173/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .svelte-kit
  ├─ build
  ├─ enigo
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  └─ static
```

### Stack trace

_No response_

### Additional context

As it seems, this is due to a [bug](https://github.com/Byron/open-rs/issues/67) in `open-rs` that has recently been [fixed](https://github.com/Byron/open-rs/pull/68). So probably, updating the dependency will fix this issue. However, the source contains some kind of [caveat](https://github.com/tauri-apps/tauri/blob/1fa729b218a2e0af57524a3b5f300f8f11ca12c9/core/tauri/src/scope/shell.rs#L317-L318) wrt how arguments are handled by this dependency.

### PR DESCRIPTION
**Pull request by thep0y**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

For specific bug details, please refer to https://github.com/Byron/open-rs/releases/tag/v4.0.0

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks for contributing! Unfortunately we can't merge this into the `dev` branch because of the MSRV bum to 1.62. We're stuck with 1.59 for dependencies that are also used on Linux :/ See the conversation here: https://github.com/tauri-apps/tauri/pull/6332 - if we change the approach in that PR, we'll also change it for this dependency if we bump it all the way up to 1.62

p.s. upgrading dependencies is handled by the renovate bot :)

**Comment by thep0y** [comment]
Downgrading `open` to `3.2.0` can also fix this bug, `3.2.0` can run on 1.59.

**Comment by FabianLars** [comment]
Tauri should already use 3.2 - we didn't lock it so `cargo update` in user's project should update it to the latest 3.x release.

**Comment by FabianLars** [comment]
3.4 is kinda buggy (more than 3.2 lol), so unpinning 3.2 makes this PR useless @lucasfernog

**Comment by lucasfernog** [comment]
IIRC 3.4 was yanked? I'm on my phone lol @FabianLars

**Comment by FabianLars** [comment]
ah you're right, nvm then :v:

**Pull request merged**
