### PR TITLE
feat(core): mark `AppHandle::restart` and `process::restart` as diverging functions

### LINKED ISSUE #10160: [feat] `AppHandle::restart` should be diverging function (`-> !`)
### Describe the problem

When I want to restart the tauri app, we should call `AppHandle<R>::restart` but it's not diverging function so I have to add `unreachable!()` to ensure the logic after restart will not executed

### Describe the solution you'd like

Make `AppHandle::restart` an diverging function (`-> !`).

As far as I found, it's already diverging (in tauri v1).

This change can be breaking so considering in v2 might be good.

Never type is not stable but diverging function is stable since rust 1.0.

https://doc.rust-lang.org/rust-by-example/fn/diverging.html

### Alternatives considered

just insert

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
closes #10160

### CODE REVIEW

**Comment by Legend-Master** [comment]
Should we also mark `exit`?

**Comment by amrbashir** [comment]
good call

**Comment by amrbashir** [comment]
actually it is not possible for `exit` since it only sends a request to `exit`, and users are free to prevent that, so we need to either leave it as is or introduce a new method called `request_exist` and mark the current one as diverging

**Comment by Legend-Master** [comment]
That makes sense, I only saw that if error process::exit part and assumed it will always exit, seems like it's detecting the error of sending the message

**Review by FabianLars — APPROVED** [review]

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
