### PR TITLE
feat(core): expose `runtime_handle` on AppHandle

### PR DESCRIPTION
**Pull request by lucasfernog**
This function will be needed by the clipboard and global shortcut plugins.

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
Is it planned to stabilize the runtime crate? Otherwise this will likely cause semver issues with rust/cargo

**Comment by lucasfernog** [comment]
I think it's time to stabilize it (I didn't want to put a v1 tag on it because of tao/wry, but so far it's been alright).
Otherwise we could just mark this as unstable (and hide from docs) since it's mostly for internal use anyway.

**Comment by FabianLars** [comment]
> Otherwise we could just mark this as unstable (and hide from docs) since it's mostly for internal use anyway.

Yeah, generally i'd be completely fine with that, i don't care _that much_ about semver strictness, but this would require the plugin and the user to always use the same tauri minor version so that it can even compile, right? I'd imagine that some unlucky users would hit this issue once in a while 😅 

I mean, we can also just try it out and see what happens and stabilize the runtime if needed later 🤷

**Comment by lucasfernog** [comment]
I think Cargo prevents that kind of thing doesn't it? It only compiles a dependency twice if they are semver incompatible. And if we need a new runtime API, we just bump the minor in the plugin, and Cargo will be forced to use that new minor.

**Comment by FabianLars** [comment]
If the crate is stable, yes. If it's not (v0) then cargo is sometimes a bit sensible. But even then it should still only cause issues if the user locks dep versions in incompatible ways (or maybe if they use git deps which cargo doesn't auto-update?) - so it should be mostly fine hopefully.

Maybe i'm mixing up different semver related issues here though idk

Edit: yeah, pretty sure I'm mixing things up a bit. nevermind me I guess.

**Pull request merged**
