### PR TITLE
feat(tauri.js) add API endpoint proxy, closes #197

### LINKED ISSUE #197: module for tauri.js proxy
This is probably the right solution to fix the Windows concerns that some people have reported.

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

The only problem I see here is the need to use file:// to load the tauri package, I had to do this because if I try to load the api.js file directly, it complains that I do not have the TS ESlint plugin.

### CODE REVIEW

**Comment by lucasfernog** [comment]
closes #197

**Comment by lucasfernog** [comment]
Well, I didn't want to create another package, but we can do that too.

**Comment by lucasfernog** [comment]
Tauri can be both a global and local dependency. 
Global for CLI usage, and local for helpers like this proxy.

**Comment by nothingismagick** [comment]
The tests on the cli will pass now, thanks to @rajivshah3 - but the Quasar example needs to have the updated tauri-webpack

**Comment by lucasfernog** [comment]
Well, we'll need to update the tauri-webpack after tauri is updated.

**Pull request merged**
