### PR TITLE
fix(rpm): use product name for output package

### PR DESCRIPTION
**Pull request by amrbashir**
ref: https://github.com/tauri-apps/tauri/pull/9375
ref: https://github.com/tauri-apps/tauri/pull/9375#issuecomment-2144997488

### CODE REVIEW

**Comment by amrbashir** [comment]
@FabianLars even though the product name is used for the output bundle, the main binary name is still used in the RPM manifest, I assume the main binary name affects how you call the binary from command line? can you test if this aligns with `.deb`?

**Comment by FabianLars** [comment]
.deb:
- .deb file uses productName as is
- binary to invoke in console is from cargo.toml
- apt knows the installed app as productName as kebab-case (!)

.rpm:
- .rpm file uses productName as is
- binary to invoke in console is from cargo.toml
- dnf knows the installed app as name from cargo.toml (!)

**Comment by amrbashir** [comment]
@FabianLars can you retest with the last commit?

**Comment by FabianLars** [comment]
as far as i can tell it behaves the same now

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
