### PR TITLE
deprecate `appWindow`

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

  Deprecation

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
Quoting myself from [discord](https://discord.com/channels/616186924390023171/803006835636306022/951777089714028554):
> idk if we actually decide to deprecate it we might as well abuse the prerelease version (like we do all the time :P ) and just remove it :shrug:

Feels kinda weird to have a big 1.0 release with deprecated APIs.

**Comment by nothingismagick** [comment]
A couple comments: you haven't ticked any of the boxes in the template. We have one, and you should use it as a member of the team. Next, there is no .changes file. Finally, presenting a justification for this enhances transparency.

**Comment by amrbashir** [comment]
Deprecating `appWindow` right now is a huge breaking change since almost all users are using it now and we are using it in our documentation, extensively. The plan was to deprecate or straight remove it in tauri v2.

**Comment by lucasfernog** [comment]
I agree that this change must be merged for v2. I think we discussed that on Discord before.

Let's try to keep breaking changes minimal and only do them where it's really needed. The JS api is where it impacts most of Tauri users.

**Comment by JonasKruckenberg** [comment]
I still feel like we should deprecate it though, to give users enough time to switch 🤔.

**Comment by amrbashir** [comment]
closing in favor of complete removal for v2 in #5136

**Pull request closed without merging**
