### PR TITLE
chore: remove unstable log features & use qualified `log::<macro>` path

### PR DESCRIPTION
**Pull request by amrbashir**

### CODE REVIEW

**Review by lucasfernog — APPROVED** [review]
we should consider adding tauri-plugin-log by default (on debug) on the app template.. it's now required to see the log::error messages (plus it's kinda required on mobile, otherwise app logs/stdout aren't visible on android and iOS)

**Comment by amrbashir** [comment]
maybe we could add an internal logger that is activated on debug only. I don't want to pollute the template with another plugin, I am already dissatisfied with the shell plugin being there by default.

**Comment by lucasfernog** [comment]
shell is there only for CTA right? and yes it sucks

**Comment by amrbashir** [comment]
yeah only in CTA template

**Pull request merged**
