### PR TITLE
Remove Typedoc Integration

### PR DESCRIPTION
**Pull request by lorenzolewis**
### What kind of change does this PR introduce?

- [x] Build-related changes

### Does this PR introduce a breaking change?

- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information
This removes any typedoc integrations that we were dependent on downstream. This dependency is now unnecessary as of this commit https://github.com/tauri-apps/tauri-docs/commit/be238d0faeba55bf7f2df868baba6ae87fe2ffc6

You can see the live build here (formatting still to be adjusted): https://beta.tauri.app/2/reference/js/event/

### CODE REVIEW

**Comment by amrbashir** [comment]
Should probably target 1.x branch and then it will be merged into dev later

**Comment by FabianLars** [comment]
Yeah, should be fine since we don't use that for the v1 docs either iirc

**Comment by lorenzolewis** [comment]
> Yeah, should be fine since we don't use that for the v1 docs either iirc

I didn't test it on the Docusaurus branch, and I'm not 100% sure on the plan yet for if we're going to maintain that one for anything on v1 (and need to keep it working) or if we're planning to move everything to the new setup.

We can either merge this one in here and then merge the same in later to the 1.x branch or can wait a bit longer to see what the docs strategy for v1 is (which I can't promise anything yet until I get v2 figured out, a lot more we're adding with all the reference documentation).

**Comment by FabianLars** [comment]
> I didn't test it on the Docusaurus branch

I did when the typedoc stuff in this repo was broken for a few weeks. But we can try running the current update-docs workflow on this branch to double check.

**Comment by FabianLars** [comment]
All good: https://github.com/tauri-apps/tauri-docs/actions/runs/5691025036/job/15425423870 / https://github.com/tauri-apps/tauri-docs/pull/1336

**Comment by lorenzolewis** [comment]
Closing in favour of https://github.com/tauri-apps/tauri/pull/7515 because git is hard 😮‍💨

**Pull request closed without merging**
