### PR TITLE
Cherry pick DMG settings to 1.x

### PR DESCRIPTION
**Pull request by hjmallon**
### What kind of change does this PR introduce?

Cherry pick from dev to 1.x

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by hjmallon** [comment]
This is now rebased and I have signed all the cherry-picked commits

**Review by FabianLars — DISMISSED** [review]

**Review by FabianLars — APPROVED** [review]
No idea why clippy is having a mental breakdown but i'll worry about that somewhere else, not in this PR.

Thanks again for the PR!

**Comment by Lurrobert** [comment]
why was it rolled back:((?
upd: not released yet. will be soon

**Comment by MystiPanda** [comment]
I just tested the latest version, but it seems that the changes did not take effect. The dmg I packaged looks like this:

image

```json
"dmg": {
        "background": "images/background.png",
        "appPosition": {
          "x": 180,
          "y": 170
        },
        "applicationFolderPosition": {
          "x": 480,
          "y": 170
        },
        "windowSize": {
          "height": 400,
          "width": 660
        },
        "windowPosition": {
          "x": 200,
          "y": 180
        }
      }
```
I noticed that the default position for two icon in the original code were set like this, and it didn't work in previous versions either. I'm not sure where the issue lies.

**Comment by FabianLars** [comment]
(I assume you used the CLI from git because it's not released yet?)

Did you build the dmg in CI like GitHub actions? If so then this is a known issue and happened before this PR too. :/

**Pull request merged**
