### PR TITLE
API example new ui

### PR DESCRIPTION
**Pull request by dawnlarsson**
## New UI
I've updated the API example UI to align more with the Tauri Theme.
image

I will follow up on a custom title bar for this when the #drag-region CSS tag has been implemented.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe: UI Update

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [X] No

### CODE REVIEW

**Comment by dawnlarsson** [comment]
(WIP)
this is still a bit rough around the edges, got some things to fix up
- Console overflow
- Custom default icon?
- Cleanup (dead CSS, js, svelte code)
- new screenshot

**Comment by nothingismagick** [comment]
How is the status of this @AlveLarsson ? We are planning on releasing the beta very soon, and would love to have this merged in.

**Comment by lucasfernog** [comment]
I'll fix the conflicts later today btw, forgot about it lol

**Comment by dawnlarsson** [comment]
This is now ready, we are only missing the title bar but that comes later when it's ready :)

**Comment by amrbashir** [comment]
Unless WRY uses the dev branch  of winit,  The titlebar will need winit's next release as it will include `begin_drag` for windows and macos.

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
