### PR TITLE
refactor(cli&bundler): avoid renaming main executable and preserve cargo name

### LINKED ISSUE #8109: [feat] displayName for package
### Describe the problem

This is probably nitpicking, but I am looking to have two separate "names" for my Tauri application.  Right now, I understand that in `tauri.conf.json` I can define `package` -> `productName`.  This is what is used to name installers, exe's, log files (if using the [plugin](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/log)), etc.  

But it also is what is used for the "user-facing" display name, for example what it is called in the Start Menu on Windows.  So for `my-app`, if I want the user to have a "user-friendly" name to search for, I need to set `productName` to `My App`.  But then the underlying executable is called `My App.exe`, which just kind of irks me lol.  I think it should be `my-app.exe`.  It just seems more professional, and more in line with what I see in other apps I have installed on my system.

### Describe the solution you'd like

Keep `productName` as the default way of naming your app.  But add an option in `package` called `displayName`, which determines the "user-facing" name of the application, while keeping file-system friendly `productName` for .exe's, etc.

### Alternatives considered

I am thinking that this would be an app manifest thing on Windows.  Not sure about Linux and Mac.

### Additional context

_No response_

### LINKED ISSUE #8349: [bug] Tauri unwantedly converts PascalCase package product name to kebab-case
### Describe the bug

The string configured as `package.productName` in tauri.conf.json in my project is "OpenDeck". This is the string I would like to be shown in start menus, docks, app launchers, software stores (e.g. GNOME Software), etc. 

However, Tauri unwantedly converts this string to "open-deck" for the output artifact names (resulting in `open-deck_2.0.0_amd64.deb` and so forth) and for the executable name (meaning that it's `open-deck` to run it from a shell). I would like these both to be `opendeck`. However, the docs don't appear to mention any property that can be changed to override this behaviour.

### Expected behavior

I should be able to specify an alternative string to use for these properties in my `tauri.conf.json` instead of having to deal with an inaccurate case conversion.

### Platform and versions

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.42.2
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.18.0
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.6
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6 (outdated, latest: 1.5.7)

[-] App
    - build-type: bundle
    - CSP: default-src 'self';
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### LINKED ISSUE #9221: [feat] firendly error output when make nsis bundle on linux but got (os error 2)
### Describe the problem

I am using `tauri cli 1.5.11`, i always get `Error failed to bundle project: No such file or directory (os error 2)` when i build nsis bundle on linux, i don't know why, then i found a issue #6743 about this error, so i think my tauri version is too low, but after i upgraded to `2.0.0-beta.9`, this error still exist.

I am so confused, so i debug the tauri cli line by line, i found my binary file name is not nsis needs, just because my `package.productionName` is `BDSM` but nsis needs `bdsm`, the error occoured at:
https://github.com/tauri-apps/tauri/blob/d349558abbefc78baf98f7837e5237f370758931/tooling/bundler/src/bundle/windows/nsis.rs#L636

Here is the error log:
```
warning: `bdsm` (bin "bdsm") generated 4 warnings
    Finished release [optimized] target(s) in 4m 08s
    Warn Cross-platform compilation is experimental and does not support all features. Please use a matching host system for full compatibility.
    Info Verifying NSIS package
    Downloading https://github.com/tauri-apps/binary-releases/releases/download/nsis-plugins-v0/NSIS-ApplicationID.zip
    Info extracting NSIS ApplicationID plugin
    Downloading https://github.com/tauri-apps/nsis-tauri-utils/releases/download/nsis_tauri_utils-v0.2.2/nsis_tauri_utils.dll
    Info validating hash
    Info Target: x64
    Info Code signing is currently only supported on Windows hosts, skipping...
    Error failed to bundle project: `No such file or directory (os error 2)`
```

### Describe the solution you'd like

I think, can we provide which file name caused `No such file or directory` like this:
```
cannot get metadata for /app/src-tauri/target/x86_64-pc-windows-msvc/release/bdsm.exe: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
closes #8109
closes #8349

### CODE REVIEW

**Comment by amrbashir** [comment]
cc @FabianLars this will affect tauri-action, can you please give this a test

**Comment by FabianLars** [comment]
> cc @FabianLars this will affect tauri-action, can you please give this a test

We already have logic in place to read the cargo.toml file so this should be an easy change. I will open a pr once this one here is merged (or earlier if i'm bored lol)

**Comment by nekename** [comment]
Hi,

I'm close to releasing a stable version of my app, and I would like to have my app's proper name in releases :P (#8349)

Could this be merged ASAP?

Thanks

**Comment by FabianLars** [comment]
We can (almost) never promise when something gets merged, but you can always use tauri from git if you can't wait for us :) <https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes> (just replace dev/1.x with this PR's branch)

**Comment by lucasfernog** [comment]
Pushed a small change to use the product name for the installers. I'm not sure about the Linux ones though - maybe we keep using the binary name? @FabianLars @amrbashir

**Comment by amrbashir** [comment]
It is fine for the installers, not sure about how it will affect linux bundle as well but should be fine to change as well, even macOS if possible. It is just a filename

**Review by lucasfernog — APPROVED** [review]

**Comment by FabianLars** [comment]
@olivierlemasle Sorry for the random ping but since you added rpm support, do you think applying this change to the rpm bundle is fine too? For reference, this is the output we have after this PR (deb changed, rpm not):
grafik

**Comment by amrbashir** [comment]
I think we can rename it manually if the underlying library doesn't support using a custom file name

**Comment by FabianLars** [comment]
I didn't look at any code, i assumed we are currently setting the output name ourselves tbh, just wasn't sure about conventions and maybe even issues with dnf. Conventions probably don't matter because afaik the new .deb naming scheme also breaks with conventions(?). I think i'd prefer the consistency this time idk

**Comment by amrbashir** [comment]
Looks like we do, I will open a PR to change that

**Comment by bukowa** [comment]
Trying to find out what's the new way to change application binary name correctly:
-  so all bundlers etc. work fine
- without using package.name as I want to publish it under different name as a crate

We can use:

```toml
[package]
name="my-crate-name"
default-run= "my-application-name"

[[bin]]
name = "my-application-name"
path = "src/main.rs"
```

Is this the way?

**Comment by bukowa** [comment]
> Trying to find out what's the new way to change application binary name correctly:
> 
> * so all bundlers etc. work fine
> * without using package.name as I want to publish it under different name as a crate
> 
> We can use:
> 
> ```toml
> [package]
> name="my-crate-name"
> default-run= "my-application-name"
> 
> [[bin]]
> name = "my-application-name"
> path = "src/main.rs"
> ```
> 
> Is this the way?

I think this is problematic, cuz of https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/src/interface/rust.rs#L846

**Pull request merged**
