### PR TITLE
feat(cli): add deno support

### PR DESCRIPTION
**Pull request by amrbashir**
ref: https://github.com/denoland/deno/issues/20738

### CODE REVIEW

**Comment by nekename** [comment]
Oh interesting, this would allow me to ditch the cargo cli.

**Review by lucasfernog — APPROVED** [review]

**Review by lucasfernog — APPROVED** [review]

**Comment by nekename** [comment]
Hey @amrbashir 

I've added `"@tauri-apps/cli": "^2.0"` to my `devDependencies`, but can't figure out how to use the CLI from within Deno.

The only solution I've found to make `deno task tauri dev` work is to add the following to the `scripts` section of my package.json:

`"tauri": "deno run -A npm:@tauri-apps/cli"`

but that doesn't seem very elegant.

**Comment by amrbashir** [comment]
@ninjadev64 This PR is not released yet, once it is released, you will be able to just have `"tauri": "tauri"` then you can just use `deno task tauri dev`

**Comment by nekename** [comment]
> @ninjadev64 This PR is not released yet, once it is released, you will be able to just have `"tauri": "tauri"` then you can just use `deno task tauri dev`

I see, thanks!

This is what I have for now: https://github.com/ninjadev64/OpenDeck/commit/fd8c5cd87792fce179822f8534debeb7e21b14f1

Do you see anything that could be improved? The CI succeeds.

**Comment by amrbashir** [comment]
That looks good, nothing to improve.

**Pull request merged**
