### PR TITLE
feat(bundler): cache bundling tools in a common dir for all projects

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [X] No

### Checklist
- [X] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [X] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by amrbashir** [comment]
On Linux, I only changed the download path of `linux-deploy` and `AppRun`, I don't even know if the script was already caching them or downloads this files each `tauri build`

**Comment by FabianLars** [comment]
Does the removal of -nc mean that it will always overwrite existing files? Not familiar with wget, sry.

I'm asking because this was the main concern I had with this PR because the appimage tooling is unversioned and it would be kinda bad if users would end up not receiving bug fixes etc because of this.

**Comment by lucasfernog** [comment]
Ahh I forgot we're shipping updates like that, I'll remove the `-nc` flag so it always downloads it.

**Comment by FabianLars** [comment]
Ah lol you _added_ the flag, gosh I can't read diffs in the GitHub mobile app 😂

**Comment by amrbashir** [comment]
maybe the `-N` flag is better to only download if newer ?

**Comment by lucasfernog** [comment]
Ahh `-N` makes sense `-N,  --timestamping              don't re-retrieve files unless newer than local`

**Pull request merged**
