### PR TITLE
fix(config): remove `deny_unknown_fields`

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
what do you think about logging unknown fields in the future (only on values _actually specified in the config_ if possible)?

**Comment by lucasfernog** [comment]
The CLI validates the schema so we're not left in the dark here. Idk if it can be improved.

**Comment by FabianLars** [comment]
Yeah, i was thinking about what if users see new features/config options and only update the cli and wonder why the config doesn't have any effect

**Comment by lucasfernog** [comment]
I don't think there's an easy way to do that using serde. Maybe we should just improve the error message instead.

**Comment by lucasfernog** [comment]
I think I'll change the CLI to pass only the merge config instead to avoid conflicts.

**Comment by lucasfernog** [comment]
Closing in favor of #4598

**Pull request closed without merging**
