### PR TITLE
fix(core/wry): implement resizing natively on Windows

### LINKED ISSUE #7388: [bug] Window without decorations has buggy window controls.
### Describe the bug

When disabling window decorations, controls are getting bugged, i.e. when resizing window from custom top bar it may just start dragging it or work as intended, or when hovering edges of window, cursor switching between default and resize

### Reproduction

```npm create tauri-app@latest```, js vanilla frontend

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="styles.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tauri App</title>
    <script type="module" src="/main.js" defer></script>
  </head>
  <body>
    <div style="height: inherit; width: inherit; display: flex; flex-direction: column;">
      <div style="width: 100%; height: 4rem; background-color: gray;" data-tauri-drag-region></div>
      <div class="custom-scroll scroll">
        <h1>Tauri</h1>
        <div style="height: 1000px;"></div>
      </div>
    </div>
  </body>
</html>
```
styles.css
```css
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif;
  margin: auto;
  width: 100vw;
  height: 100vh;
}

.custom-scroll {
	-ms-overflow-style: none; /* for Internet Explorer, Edge */
	scrollbar-width: none; /* for Firefox */
	overflow-y: scroll;
}

.scroll::-webkit-scrollbar {
	height: 6px;
	width: 12px;
}

.scroll::-webkit-scrollbar-track {
  background-color: rgba(0, 0, 0, .0);
  border-radius: 3px;
}

.scroll::-webkit-scrollbar-thumb {
  background-color: transparent;
  border-radius: 3px;
}

.scroll:hover::-webkit-scrollbar-thumb {
  background-color: rgba(11, 11, 13, .2);
}
```
In tauri config: enable startDragging, disable decorations

### Expected behavior

Expected behavior like in electron app (see video)

https://github.com/tauri-apps/tauri/assets/54988116/5440c07e-1e6a-484e-9524-76c98ffbfb18

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19044 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC:
        - Visual Studio Build Tools�2019
        - Visual Studio Community�2019
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-gnu (default)
    - node: 18.12.1
    - pnpm: 8.1.1
    - yarn: 3.4.1
    - npm: 9.6.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../src
    - devPath: ../src
```

### Stack trace

_No response_

### Additional context

_No response_

### LINKED ISSUE #9464: [bug] Issue with Resizing Window on Windows 11 at Non-100% Display Scale
### Describe the bug

When `decorations=false` and `resizable=true` are set for the `webview_window`, when the display scale is not equal to 100%, the right and bottom edges of the window cannot be dragged to resize the window. It works normally when the scale is 100%.

### Reproduction

_No response_

### Expected behavior

_No response_

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22635 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 8.15.7
    - yarn: 1.22.21
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-alpha.4
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### LINKED ISSUE #9510: [bug] inability to change the height/length of the window using the drag area
### Describe the bug

Hi. When trying to resize a window in the drag-and-drop area, it's difficult because, as far as I know, there's 1 pixel highlighted there that you can grab to change the window. There is no way to change the window at all at the edges, and when you try to double-click on the edge of the window, the application unfolds with an artifact

### Reproduction

https://github.com/tauri-apps/tauri/assets/84803793/6391b6e5-9e0f-454e-b10d-815b6355c017

### Expected behavior

Make it so that when the cursor changes the borders of the window, the drag function is disabled. Maybe you can somehow add an event listener that will read the current state of the cursor

image

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.97
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - yarn: 1.22.19
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.15
    - tauri-build [RUST]: 2.0.0-beta.12
    - wry [RUST]: 0.39.1
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.8
    - @tauri-apps/cli [NPM]: 2.0.0-beta.13

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
Done in 6.82s.
```

### Stack trace

_No response_

### Additional context

_No response_

### LINKED ISSUE #9881: [bug] There is an issue with the window dragging size in the v2 version.
### Describe the bug

The window is set with **decorations: false** attribute. The top and left sides are displayed normally, but the right and bottom edges are not.

https://github.com/tauri-apps/tauri/assets/55067857/1ea9cb9a-973a-4213-bbd8-215a08646ff9

And there are also some issues with the response when dragging and changing the window on the top and left sides. Sometimes when my mouse goes out, the window remains unchanged, which is normal in v1 version.

### Reproduction

_No response_

### Expected behavior

_No response_

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.20.0
    - yarn: 1.22.22
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.20
    - tauri-build [RUST]: 2.0.0-beta.16
    - wry [RUST]: 0.40.0
    - tao [RUST]: 0.28.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.12
    - @tauri-apps/cli [NPM]: 2.0.0-beta.18

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
closes #7388
closes #9510
closes #9464
closes #9881

ref #9268
ref #9053
ref #8770
ref #8750
ref #4012

### CODE REVIEW

**Comment by FabianLars** [comment]
Sorry for the long delay on the review here...

The resizing itself works really well, good job!

You said you wanted to add support for the controls too, right? Asking because if users imitate native controls then the resize handles will conflict with it at the border a bit.
Even if not, imo it'd be a good tradeoff (especially if we add bordered mode too idk), just wanna be upfront about it.

**Comment by amrbashir** [comment]
> You said you wanted to add support for the controls too, right? Asking because if users imitate native controls then the resize handles will conflict with it at the border a bit.
> Even if not, imo it'd be a good tradeoff (especially if we add bordered mode too idk), just wanna be upfront about it.

That should be in another PR, and most likely resize handles will take priority over buttons

**Comment by FabianLars** [comment]
> That should be in another PR

Of course

> and most likely resize handles will take priority over buttons

Yeah, that's how this PR already behaves with html/js buttons which is why i'm asking, cause this is different to native/electron. But again, i'm fine with that, just wanted to talk about it once so we're all on the same page.

**Comment by amrbashir** [comment]
> cause this is different to native/electron.

Sure native behaves differently but that's out of scope of this PR since we can't achieve similar things as native (not yet at least) but I am curious how electron behaves with WCO or custom HTML buttons.

**Comment by FabianLars** [comment]
in vscode for example (and other random electron apps I have installed) the buttons behave like native == only have a 1px resize handle (feels less than 1px tbh). Basically as if the buttons float above the resize handles.

**Comment by amrbashir** [comment]
Just tested electron and I don't see them doing anything special, the resize border size is consistent whether there is a button or not so it is safe to say they have the same behavior as us (maybe our resize border size is a little bit bigger?)

**Comment by FabianLars** [comment]
Maybe the apps i tested used WCO 🤷 

> maybe our resize border size is a little bit bigger?

Now that you mention it, yes that's also the case. (imo good because for me electron's handles are too small)

**Comment by amrbashir** [comment]
Can we merge this and get it in the hand of users to test so we can see if there is any bugs or if the border size needs a bit of tweaking?

**Comment by FabianLars** [comment]
fine with me

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
