### PR TITLE
chore(ci): use a separate covector workflor for 1.x

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lucasfernog** [comment]
Using a dedicated workflow for 1.x prevents issues when merging 1.x back into dev.

**Review by amrbashir — COMMENTED** [review]
I honestly don't think we should be merging `1.x` back to `dev`, they are different branches now, that will have their own history, any changes should be backported to `1.x` manually and in its own PR IMO.

**Comment by lucasfernog** [comment]
We're still working on v1 kinda actively, so cherry picking each PR is slow and polutes the pull requests tab :cry:

**Review by amrbashir — APPROVED** [review]
alright, I guess we could keep it that way for now

**Pull request merged**
