### PR TITLE
feat(bundler): cache appimage bundle tools

### PR DESCRIPTION
**Pull request by brian14708**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
This is what the `-N` flag is for, it enables wget's timestamping so that it only downloads it if the remote file is newer.
With this if check it would never re-download the files even if there's a new version which happens relatively regular.

Thank you nonetheless.

**Comment by brian14708** [comment]
> This is what the `-N` flag is for, it enables wget's timestamping so that it only downloads it if the remote file is newer.

After some testing, I've found that `-N` and `-O` can't be used together and the `-q` option hides the warning.

Quote [man](https://man7.org/linux/man-pages/man1/wget.1.html):
>           For this reason, -N (for timestamp-checking) is not supported
>           in combination with -O: since file is always newly created,
>           it will always have a very new timestamp. A warning will be
>           issued if this combination is used.

**Comment by brian14708** [comment]
> With this if check it would never re-download the files even if there's a new version which happens relatively regular.

I've modified the code to keep using `wget -N`, if you are still interested. 351b676b09584a06daab5e6c0a19ab6811a309ea

**Comment by FabianLars** [comment]
> After some testing, I've found that -N and -O can't be used together and the -q option hides the warning.

Ahh interesting!

> I've modified the code to keep using wget -N, if you are still interested.

Yep, i am interested in that! Buuut i can't re-open PRs after there was a force-push (or branch recreation), see [isaacs/github#361](https://togithub.com/isaacs/github/issues/361), sorry for closing it too quickly, didn't know that this is a thing 😅

**Pull request closed without merging**
