### PR TITLE
fix(cli): use `matched_path_or_any_parents` when checking if a file is ignored

### LINKED ISSUE #8901: [bug] specifying folder to `.taurignore` doesn't exclude files in the folder for watching
### Describe the bug

specifying folder to `.taurignore` doesn't exclude files in the folder for watching

### Reproduction

1. create simple tauri app
2. write `.taurignore` that excludes some folder
3. `cargo tauri dev`
4. edit files in the excluded folder
5. cargo tauri rebuilds the app

### Expected behavior

exclude specified folder from watching

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.10.0
    - pnpm: 8.8.0
    - yarn: 1.22.19
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.6.0
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - tauri-cli [RUST]: 1.5.10
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: web/out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```
```


### Stack trace

```text
N/A
```

### Additional context

In the following code, [`matched`](https://docs.rs/ignore/0.4.22/ignore/gitignore/struct.Gitignore.html#method.matched) is used but it seem tauri should use [`matched_path_or_any_parents`](https://docs.rs/ignore/0.4.22/ignore/gitignore/struct.Gitignore.html#method.matched_path_or_any_parents)

https://github.com/tauri-apps/tauri/blob/258494bd247b6d36485bf16bf7184b93fd299da9/tooling/cli/src/interface/rust.rs#L267

I'm going to write pull request that fixes this

### PR DESCRIPTION
**Pull request by anatawa12**
Fixes #8901

### CODE REVIEW

**Comment by amrbashir** [comment]
Could you give an example of the .taurignore you're trying to fix?

**Comment by anatawa12** [comment]
image

This taurignore should ignore changes in `web` folder from watching but doesn't. changes in `.next` folder will cause rebuilding whole app.

**Comment by amrbashir** [comment]
@anatawa12 sorry for the long delay, I just tested the ignore file you posted and I didn't see any issues, all files were ignored except package.json

Would you mind providing a minimal repro?

**Comment by anatawa12** [comment]
https://github.com/anatawa12/tauri-issue-8901 is the repository that I can reproduce this problem.

clone and run `cargo tauri dev` and then editing `web/ignored/test` file will cause rebuild of the crate.
image

**Review by amrbashir — APPROVED** [review]
Thank you

**Pull request merged**
