### PR TITLE
feat: #1528 wix supports custom templates  

### PR DESCRIPTION
**Pull request by Cupnfish**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [X] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)
 #1528
**Other information:**

### CODE REVIEW

**Review by nothingismagick — APPROVED** [review]

**Review by nothingismagick — CHANGES_REQUESTED** [review]
Ooops. We need a .changes file here please.

**Review by nothingismagick — APPROVED** [review]

**Comment by lucasfernog** [comment]
Can we implement some kind of solution to merge two wix files? This solution is a little scary since the user would have trouble maintaining Tauri changes.

**Comment by Cupnfish** [comment]
I haven’t come up with any other ideas yet, but I think this feature is necessary, so if anyone has a better idea, feel free to share.

**Comment by lucasfernog** [comment]
I need to try merging two XMLs using serde, but i'm busy with the plugin system right now.

**Comment by Cupnfish** [comment]
Do I need to close the PR?

**Comment by lucasfernog** [comment]
Let's wait to see if I can come up with a solution that simplifies your life :)

**Comment by lucasfernog** [comment]
I think using [Fragments](https://wixtoolset.org/documentation/manual/v3/xsd/wix/fragment.html) is the right way to do this.

**Comment by lucasfernog** [comment]
I've finished implementing Wix fragments support. We can also add support to [WIX include files](https://documentation.help/WiX-Help/wxi.htm) if you need.

**Comment by Cupnfish** [comment]
Thank you for your help.
It’s great, I love it. WIX include files is necessary.
In addition, I still have a problem to solve, the current WIX template is the default download edge webview, for other rust projects do not need this, packaging with this is very inconvenient, there is no way to solve this problem?
I think I should mention a new issue.
#1606

**Comment by lucasfernog** [comment]
Since you're using the bundler outside Tauri, i think we can reconsider this :)

**Review by lucasfernog — APPROVED** [review]

**Comment by lucasfernog** [comment]
If we start getting attention with the bundler as a library, we should consider moving it to its own repo.

**Comment by Cupnfish** [comment]
Thank you

**Pull request merged**
