### PR TITLE
fix(cli.rs): inline dialoguer & console until they publish, fixes #1492

### LINKED ISSUE #1492: [Win] Modifiers keys make init script crash
**Describe the bug**
On windows when using the command tauri init from the @tauri-apps/cli package if any of those keys, left or right, CTRL , ALT, AltGr, SHIFT and Caps Lock are pressed it makes the script crash

**To Reproduce**
In a new folder
1. yarn init
2. yarn add @tauri-apps/cli
3. At any prompt, press any of the key, the script will crash

**Expected behavior**
The script should take the input

**Platform and Versions (please complete the following information):**

OS: Windows 10
Node: 15.12.0
NPM: 7.9
Yarn: 1.22.5
Rustc: 1.51.0

It seems to be related to the crates dialoguer & console

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

https://github.com/mitsuhiko/dialoguer/issues/110#issuecomment-825081172

### CODE REVIEW

**Comment by lucasfernog** [comment]
I'll test this on Windows later.

**Comment by lucasfernog** [comment]
> I'll test this on Windows later.

It works!

**Comment by nothingismagick** [comment]
Regarding the licensing for `console` and `dialoguer` - they are both MIT licensed, so we are not required to do anything at all in the context of this soft fork. It would be "nice" of us to keep their license info though.

**Comment by lucasfernog** [comment]
Clippy warnings being fixed on another PR.

**Pull request merged**
