### PR TITLE
chore(tauri.js): Add prepare script

### PR DESCRIPTION
**Pull request by rajivshah3**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Adds a [`prepare` script](https://docs.npmjs.com/misc/scripts.html) to `tauri.js`. This script is run before publishing and when running `yarn` to install dependencies to ensure that the TS files are built.

### CODE REVIEW

**Comment by jbolda** [comment]
This is partly related, but do we need to configure for the `npm publish` to use the new `dist`?

**Comment by rajivshah3** [comment]
> do we need to configure for the `npm publish` to use the new `dist`?

Since the intended behavior of the `prepare` script is to run after `yarn`/`npm install` and before `yarn publish`/`npm publish`, I don't think any further configuration is needed. The `dist` folder should be uploaded with the rest of the package when it's published

**Comment by jbolda** [comment]
Perhaps I'm missing some configuration, but won't this include both the `dist` and the `src`? No need for the redundency and it's just extra stuff that needs to be downloaded.

**Comment by rajivshah3** [comment]
Oooh, that's a good point, yeah. So there are two options if you want to exclude `src` from the published package:

- Add `dist` to the `files` property of the `package.json`:
  - `react-native-community/cli` did this: https://github.com/react-native-community/cli/blob/master/packages/cli/package.json#L13-L16
  - See [`files` section](https://docs.npmjs.com/files/package.json#files) of the `package.json` docs
- Add `src` to `cli/tauri.js/.npmignore`

**Comment by jbolda** [comment]
I tend to prefer the `files` property myself. It is more explicit and lessens the chance of accidentally including newly added files.

**Pull request merged**
