### PR TITLE
fix(core): add windows 7 notification support

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
I don't like that it's not an opt-in thing :/ because many people will not make use of this method. But I think we have too many features as-is, so I'm content.

~~Edit: Without knowing too much about the notifications feature, why can't this be a check inside `show`? That calls out to the `notify_win7` method?~~

EditEdit: I'm stupid and should pay attention to what's happening on discord

**Comment by lucasfernog** [comment]
Basically the problem is that we need the event loop to be running and the notification's show method to be called in the main thread. The current show API cannot do that.

**Comment by lucasfernog** [comment]
I could also introduce a `windows7` or `compatibility` Cargo feature that changes the `show` method signature.

**Comment by JonasKruckenberg** [comment]
> I could also introduce a `windows7` or `compatibility` Cargo feature that changes the `show` method signature.

Hmmm, I mean on paper that is the most elegant solution IMO. But we already have so many features and this would just be one more thing to document 🤔 So I'm fine with whatever you decide.

If you go the feature route, name it `windows7` (or `windows7_compat`) though, we might have more specialized bug fixes for win7 in the future

**Comment by amrbashir** [comment]
I am in favor of adding this behind a feature flag. Most tauri apps won't care about win7 and those who want to support, will need to pay the penalty of having to include another crate.

**Comment by lucasfernog** [comment]
I've added the feature flag but kept the two different names for better documentation. I also put a deprecation warning on `show()` in case `windows7-compat` is enabled so you don't accidentally use it.

**Comment by lucasfernog** [comment]
Done. Tomorrow I'll add the Windows 7 section in the distribution guide (webview install + notifications).

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
