### PR TITLE
fix(codegen): serialize template tags, closes #4410

### LINKED ISSUE #4410: [bug] HTML <template> element empty when serving bundled files
### Describe the bug

When `build.devPath` is a path to a directory, `<template>` elements are empty despite having contents in the source files:

```
<!-- ... -->
<template>
	<tr>
		<td class="id"></td>
		<td class="desc"></td>
	</tr>
</template>
<script src="common.js"></script>
<!-- ... -->
```

image

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```shell
Environment
  › OS: Alpine Linux 3.16.0 X64
  › Node.js: 16.15.0
  › npm: 8.12.1
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: Not installed!
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ .git
  └─ src-tauri
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lucasfernog** [comment]
Closes #4410

**Review by amrbashir — APPROVED** [review]

**Comment by TonyLuo** [comment]
hi @lucasfernog , I am trying to use tauri with vue 3, may I know when will this fix be released?

**Comment by TonyLuo** [comment]
I tried to use branch fix/template-html, but  vue-router didn't work when build into bundle, it only worked in tauri dev mode

```
[package]
name = "app"
version = "0.1.0"
description = "app Client"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
# tauri-build = { version = "1.1.1", features = [] }
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "fix/template-html", features = [] }

# [dependencies]
# serde_json = "1.0"
# serde = { version = "1.0", features = ["derive"] }
# tauri = { version = "1.1.1", features = ["http-all", "shell-all", "system-tray", "window-all"] }
[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# tauri = { version = "1.1.1", features = ["http-all", "shell-all", "system-tray", "window-all"] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "fix/template-html", features = ["http-all", "shell-all", "system-tray", "window-all"] }
# cocoa = "0.24.0"
window-vibrancy = "0.3.0"
window-shadows = "0.2.0"
percent-encoding = "^2.2"
# tauri-plugin-positioner = {git = "https://github.com/JonasKruckenberg/tauri-plugin-positioner", branch = "main"}
# tauri-plugin-localhost = "0.1.0"
# portpicker = "0.1"

[dependencies.tauri-plugin-store]
git = "https://github.com/tauri-apps/tauri-plugin-store"
branch = "dev"
[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
cocoa = "0.24.0"

```

**Comment by lucasfernog** [comment]
We're planning a patch next week.

**Comment by lucasfernog** [comment]
@TonyLuo please file a separate issue with a repo we can use to reproduce it.

**Pull request merged**
