### PR TITLE
chore: fixed resolver issue

### PR DESCRIPTION
**Pull request by martinfrances107**
This PR resolves  a warning seen while running cargo update

warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by amrbashir** [comment]
Oh looks like you didn't sign your commits and I can't merge the PR unless they are signed. You need to setup [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), then you can sign past commit like [this](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits/1123928#1123928) for example. 

Also could you rebase and target `1.x` branch which will be merged later into `dev`?

**Comment by martinfrances107** [comment]
Thank you and Ah I screwed up again .. I push the amended and signed version to dev ... one sec I will target 1.x as you asked.

**Comment by amrbashir** [comment]
You need to rebase your branch as well to have `1.x` as a base not `dev` so you don't pull this changes. Might be easier to just close this PR and open a new one.

**Comment by amrbashir** [comment]
Closed in favor of https://github.com/tauri-apps/tauri/pull/7747

**Comment by martinfrances107** [comment]
> You need to rebase your branch as well to have 1.x as a base not dev so you don't pull this changes. Might be easier to just close this PR and open a new one.

Agreed here is the new PR https://github.com/tauri-apps/tauri/pull/7747

**Pull request closed without merging**
