### PR TITLE
feat(core): add dangerous option to disable compile time CSP injection

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
I think the naming could be improved here, `disable_asset_csp` makes it sound as if it would disable the whole csp mechanism. I have no idea for better names either though

**Comment by lucasfernog** [comment]
Is `dangerous_disable_asset_csp_injection` better? @JonasKruckenberg this is so hard :joy:

**Comment by lucasfernog** [comment]
I guess `dangerous_disable_asset_csp_modification` is the least ambiguous choice.

**Comment by JonasKruckenberg** [comment]
I mean it's a mouthful 😅 but it's the best name yet so let's go 👍🏻

**Comment by lucasfernog** [comment]
It's supposed to be. It's a dangerous config, we need to do our best to discourage people to even write it, and if they do, force them to make typos to regret enabling it :joy: :joy:

**Pull request merged**
