### PR TITLE
feat: Add `on_app_ready` to `Builder`

### PR DESCRIPTION
**Pull request by lemarier**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by wusyong — APPROVED** [review]

**Comment by lemarier** [comment]
We should merge https://github.com/tauri-apps/tauri/pull/2263 first

**Comment by lucasfernog** [comment]
@lemarier we could leverage the existing `run` callback instead of adding a new API, what do you think? See https://github.com/tauri-apps/tauri/blob/6e0dbf639ac2c79e00fee9270a2ca8e613dc1f98/core/tauri/src/app.rs#L330

**Comment by lemarier** [comment]
> @lemarier we could leverage the existing `run` callback instead of adding a new API, what do you think? See
> 
> https://github.com/tauri-apps/tauri/blob/6e0dbf639ac2c79e00fee9270a2ca8e613dc1f98/core/tauri/src/app.rs#L330

You are totally right!

**Comment by amrbashir** [comment]
@lucasfernog @lemarier 

I think users who use `setup` hook would like to have this.
It would be good for logic flow
```rs
tauri::Builder::default()
    .setup()
    .on_app_ready() // app is ready to run
    .run() // run should be for runtime events
```

**Pull request closed without merging**
