### PR TITLE
feat(examples): add vue cli app example

### PR DESCRIPTION
**Pull request by nklayman**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Add example
 
**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Example created with latest version of vue cli and latest [vue cli plugin tauri](https://github.com/tauri-apps/vue-cli-plugin-tauri).

### CODE REVIEW

**Comment by nklayman** [comment]
@jbolda The vue cli plugin has a custom build command in place of `tauri build`. How should I use that instead? I could just skip `tauri build` and make `yarn build` run the command via the `package.json` scripts.

**Comment by jbolda** [comment]
We just call `yarn tauri:source:build` and `yarn tauri:prod:build` in the production smoke tests and dev smoke tests, respectively. As long as that script targets your cli plugin, it should Just Work™️.

I noticed there was already `"tauri:build": "vue-cli-service tauri:build"` in the package.json. Is that recursively calling itself? I'm not familiar with the `vue-cli-service` in all honesty.

**Comment by nklayman** [comment]
The `vue-cli-service tauri:build` runs the plugin's build command, which runs the vue cli build and then calls `tauri build` by importing the api file and running the exported function.

**Comment by nklayman** [comment]
Since all I can run is a prod smoke test anyway, would it be fine to just have the tests in the vue-cli-plugin-tauri repo? I already have an e2e test there that I can hook up to github actions.

**Comment by jbolda** [comment]
Ah, I see, nifty. If I am reading this right, you could possibly have this run from source by making the `const build = require('tauri/dist/api/build')` configurable to point at the source.

I guess I'm of the opinion that if we are going to have smoke tests run in this repo, it should use source. The prod tests are less worthwhile, but are there to catch obvious oversights (which in the case of this example, would have, but you caught it right away 😎). I imagine we will want to add more of these plugins for the various frameworks over time so maybe it is worth establishing "best practices for integration" that you and the @tauri-apps/admins are comfortable with.

That being said, if you are e2e testing in the separate repo for prod. Is there some value I'm not seeing with adding it in this repo also testing for prod? I believe the source test _does_ make a lot of sense, but that obviously requires changes to the plugin. Looking to find the right balance of catching mistakes vs adding more things here that need to be maintained. It already sounds as if there is some interest in not having any examples in this repo.

**Comment by nothingismagick** [comment]
The added value in having it here is that we will know if changes break the smoke test.

**Comment by jbolda** [comment]
But it only creates that value if we test it against source, right?

**Comment by nothingismagick** [comment]
Yeah, we need to wire that up (the test against source).

**Comment by jbolda** [comment]
Is it worth merging this in so at least there is easy access to a manual test, and then follow up PR the wiring?

**Comment by nothingismagick** [comment]
Agreed. Then we can work on that in the meantime.

**Pull request merged**
