### PR TITLE
[feat] Add Persian as available languages for NSIS installers.

### PR DESCRIPTION
**Pull request by amirHdev**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
Relevant issue: #6906 
Relevant PR: #6940

### CODE REVIEW

**Review by FabianLars — DISMISSED** [review]
Thank you!

**Comment by amirHdev** [comment]
> Thank you!

Should I do anything for Merging Block ?

**Comment by FabianLars** [comment]
Oh yeah, you need to setup [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), then you can sign past commit like [this](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits/1123928#1123928) for example.

I really wish github would complain about missing signatures more prominently, so it's easier to spot _before_ approving a PR 😅

**Comment by amirHdev** [comment]
@FabianLars 

I did . Thanks for your guide .

**Comment by FabianLars** [comment]
The first commit is still unsigned so you have to try my second link again (if you use the top answer, replace `development` with `dev` like: `git rebase --exec 'git commit --amend --no-edit -n -S' -i dev`) and then _force_ push via `git push --force` to overwrite the remote branch ;)

I really wish this part wouldn't be that finicky, it's really unfriendly for new contributors :/

**Comment by amirHdev** [comment]
@FabianLars 
I reseted and pushed as a new commti

**Review by FabianLars — APPROVED** [review]
Thanks again :D

**Pull request merged**
