### PR TITLE
feat: customize button texts of message dialog

### LINKED ISSUE #4709: [feat] Modern dialog styles on Windows
### Describe the problem

On Windows the dialogs use a very old style.

Current
image

Default Windows 11 (by embeding an rc file)
image

### Describe the solution you'd like

Use the modern styles by default.

### Alternatives considered

Embedding a manifest file as described by the native dialog docs:

https://crates.io/crates/native-dialog
https://github.com/balthild/native-dialog-rs/tree/d2ddd443f8c01e92dc22cc8132159c1b9598eaca/examples/windows_manifest

Usage:

build.rs
```rs
extern crate embed_resource;

fn main() {
  tauri_build::build();
  embed_resource::compile("program.rc");
}
```

program.rc
```
#define RT_MANIFEST 24
1 RT_MANIFEST "program.manifest"
```

program.manifest
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <assemblyIdentity
            version="1.0.0.0"
            processorArchitecture="*"
            name="Balthild.NativeDialog.Example"
            type="win32"
    />
    <description>Rust Manifest Example</description>
    <dependency>
        <dependentAssembly>
            <assemblyIdentity
                    type="win32"
                    name="Microsoft.Windows.Common-Controls"
                    version="6.0.0.0"
                    processorArchitecture="*"
                    publicKeyToken="6595b64144ccf1df"
                    language="*"
            />
        </dependentAssembly>
    </dependency>
    <asmv3:application>
        <asmv3:windowsSettings>
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True/PM</dpiAware>
            <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
        </asmv3:windowsSettings>
    </asmv3:application>
</assembly>
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by meowtec**
Demo:
Screenshot 2022-08-11 233900

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

Now we can show message dialog with customize buttons.
Limit: we can have at most two buttons. If need more buttons, the dialog API should have breaking change. I have no idea about the best solution.

### CODE REVIEW

**Comment by meowtec** [comment]
This PR will be ready after https://github.com/PolyMeilex/rfd/pull/76 be merged.

**Comment by lucasfernog** [comment]
Nice PR!

**Comment by meowtec** [comment]
While there is a new problem: the dialog level (Info / Warning / Error) is not implemented in the new message dialog.
I am trying to complete it but got stuck at https://github.com/microsoft/win32metadata/issues/968

**Comment by riverar** [comment]
I'm not familiar with Tauri architecture yet but beware that your manifest may need external edits, may get overwritten, etc. for users that need to add identity, enable high-DPI, add registration-free coclass entries, etc.

**Comment by meowtec** [comment]
> I'm not familiar with Tauri architecture yet but beware that your manifest may need external edits, may get overwritten, etc. for users that need to add identity, enable high-DPI, add registration-free coclass entries, etc.

I think that all manifests should be added by tauri, and provide some config option to users if necessary. Just like what electron does: https://github.com/electron/electron/pull/14596

**Comment by meowtec** [comment]
Test failed:
```
  process didn't exit successfully: `D:\a\tauri\tauri\target\debug\deps\tauri-66d30672674b2f8e.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

Seems because common controls v6 was not used when testing. I am unfamiliar with the `restart` crate and don't know how to fix it.
@lucasfernog Could you give some help?

**Comment by lucasfernog** [comment]
@meowtec it's not related to the restart crate; even if you remove both `restart` and `app-updater` from the workspace and run `cargo test --features dialog-all` it fails with the same error. Seems like we'd need to enable common controls v6 on the unit test runner itself?

**Comment by lucasfernog** [comment]
Fixed with a trick @meowtec :P

**Comment by lucasfernog** [comment]
Is `okLabel` and `cancelLabel` good names for this on the JS API? Example:
```ts
ask('something?', { okLabel: 'Sure', cancelLabel: 'Definitely not' })
```

**Comment by lucasfernog** [comment]
Implements #3455

**Review by lucasfernog — APPROVED** [review]

**Comment by amrbashir** [comment]
and #2147

**Pull request merged**
