### PR TITLE
Fix(api): Window size and position returning wrong class (fix: #2599)

### LINKED ISSUE #2599: Javascript API types incorrect when reading physical size
When using the Tauri API in typescript, the intellisense is not correct, (and therefore the typescript declarations are wrong?)  Specifically the API I notice this issue is when reading the physical size.

```typescript
const size = await api.window.appWindow.innerSize(); // { height: yyy, width: xxx}
size.toLogical(...); // <--- [Error] toLogical does not exist on size
```

My guess is that when sending the rust props over to javascript, the prototypes or methods are lost and only the values are passed. However the typescript typings are assuming you have a constructed object.

### PR DESCRIPTION
**Pull request by sirgallifrey**
fix #2599

**What kind of change does this PR introduce?** (check at least one)
- [X] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [ ] Yes. Issue #___
- [X] No

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Added the changed apis to Examples/api so that it can be used to test it in the future.
It looks like this:
Screen Shot 2021-09-21 at 15 39 58

Curious fact is that, for me innerSize always return the same value for a given monitor. Is that a know bug?
Also I noticed the transparent checkbox does not work, and resizable only works after changing it at least once.

### CODE REVIEW

**Comment by sirgallifrey** [comment]
I still need to do this: "A change file is added if any packages will require a version bump due to this PR per "

**Comment by sirgallifrey** [comment]
changes file added

**Comment by FabianLars** [comment]
Can you change the base branch to the `next` branch?

**Comment by sirgallifrey** [comment]
I changed through github and now it's showing a lot of changes, I'll try rebasing, if it does not work I might create a new PR to have it clean

**Comment by sirgallifrey** [comment]
rebase worked like a charm

**Review by lucasfernog — APPROVED** [review]

**Comment by lucasfernog** [comment]
Amazing work specially the example changes, thanks!

**Pull request merged**
