### PR TITLE
Refactor tauri.js to move command code outside of bin files

### PR DESCRIPTION
**Pull request by nklayman**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
The goal of this PR is to move the code run by cli commands to separate files where they are exported as functions that take a config argument. This allows other libraries to import and run these functions with custom config (such as the vue cli plugin), as well as making the commands more testable. Now, the bin files only parse args and call the command functions.

### CODE REVIEW

**Comment by lucasfernog** [comment]
Nice PR, I wanted to do it but i'm stuck with the no-server mode. Can you move the code outside of bin files to an "api" folder, instead of "helpers"? It will be easier to find these files.

**Comment by nklayman** [comment]
@lucasfernog done. I plan on updating the dir structure when I make the typescript pr as well.

**Comment by nothingismagick** [comment]
https://github.com/tauri-apps/tauri/pull/140/checks?check_run_id=342574963#step:3:20

**Comment by nklayman** [comment]
My bad, missed the import in the tests. So much for vscode's auto-update imports.

**Comment by nothingismagick** [comment]
It's still going to fail - you need to change L34 in `cli/tauri.js/jest.config.js`

**Pull request merged**
