### PR TITLE
fix: assert config.bundle.identifier to be only alphanumeric, hyphens or dots. closes #4359

### LINKED ISSUE #4359: [bug] Apple Notorization fails if bundle identifier have special chars like underscores `_`
### Describe the bug

If bundle identifier have a special character like underscore `_`, bundling for MacOS with code signing will fail without a clear reason.

Its not a big deal, but it might save another developer couple hours figuring it out. 

ex:
```json
{
    "$schema": "../node_modules/@tauri-apps/cli/schema.json",
   ...,
    "tauri": {
        ...,
        "bundle": {
            ...,
            "identifier": "com.tauri.tauri_app_example",
        },
}
```

it will output something like this:

```
  Notarizing /Users/.../src-tauri/target/universal-apple-darwin/release/bundle/macos/prodcutname.app

        Info notarization started; waiting for Apple response...

Error running CLI: failed to bundle project: Apple failed to notarize your app. No errors getting notarization info.

       Date: 2022-06-16 02:57:19 +0000
RequestUUID: xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxx
     Status: invalid

: Apple failed to notarize your app. No errors getting notarization info.

       Date: 2022-06-16 02:57:19 +0000
RequestUUID: xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxx
     Status: invalid
```

### Reproduction

1. create a new tauri app with underscored identifier in the config
2. setup code signing for mac
3. run `tauri build`

### Expected behavior

It will fail.

### Platform and versions

```shell
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.15.0
  › npm: 8.10.0
  › pnpm: 6.11.0
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13 (outdated, latest: 1.0.0)
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.15,
  › tauri-build [RUST]: 1.0.0-rc.13,
  › tao [RUST]: 0.10.0,
  › wry [RUST]: 0.18.2,

App
  › build-type: bundle
  › CSP: unset

App directory structure
  ├─ dist
  └─ src-tauri
```

### Additional context

proposed solutions:

either:
1. auto remove special chars from identifier
`com.tauri.example_app` -> `com.tauri.exampleapp`
2. throw a warning during the build time that it might cause problems with Notorization
3. do not allow identifiers with special chars

I would love to hear an expert input on this. Will push a fix when we settle on the right solution

### PR DESCRIPTION
**Pull request by imadbz**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by imadbz** [comment]
closes https://github.com/tauri-apps/tauri/issues/4359

**Comment by imadbz** [comment]
I also updated documentation in this pull request: https://github.com/tauri-apps/tauri-docs/pull/659

should be approved together.

**Comment by FabianLars** [comment]
Just for visibility i copy-paste my comment from the tauri-docs pr:
> The config docs for the website are auto generated from the tauri repo.
This https://github.com/tauri-apps/tauri/blob/dev/core/tauri-utils/src/config.rs is the main file. Building the cli in the tauri repo then regenerates this file https://github.com/tauri-apps/tauri/blob/dev/tooling/cli/schema.json (For this kinda change manually changing both should be fine).

**Comment by imadbz** [comment]
ok! updated docs on main repo too

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
