### PR TITLE
feat: expose `set_title` for MacOS tray

### PR DESCRIPTION
**Pull request by vojty**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by vojty** [comment]
Any help on finishing this PR would be appreciated.

**Review by lucasfernog — APPROVED** [review]
Nice work, thank you!

**Comment by lucasfernog** [comment]
Would be really really nice if you could setup commit signing for next time, but nice PR :heart:

**Comment by vojty** [comment]
wow I didn't expect so quick reaction, thanks a lot ❤️

**Comment by fcoury** [comment]
I am currently using this feature, and loving it.

Quick question though: is there a way already or are you planning on allowing usage of the tray with no icons, just text?

**Comment by FabianLars** [comment]
@fcoury Feel free to open a feature request for that one :v:

**Pull request merged**
