### PR TITLE
refactor(example): svelte imports

### PR DESCRIPTION
**Pull request by geocine**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
This PR updates the imports for `exit` and `relaunch` on svelte example due to change at #1667

### CODE REVIEW

**Comment by nothingismagick** [comment]
@geocine - please use the PR template properly and put the information there - instead of in the subject line.

**Comment by nothingismagick** [comment]
Also, if you plan on contributing more in the future, we do expect contributors to sign their commits with gpg.

**Review by nothingismagick — APPROVED** [review]

**Comment by geocine** [comment]
Ok sorry I somehow followed how he did it here #1667, I will take note of it , I will figure out the GPG

**Comment by nothingismagick** [comment]
> Ok sorry I somehow followed how he did it here #1667, I will take note of it , I will figure out the GPG

I understand - but still its always better to keep the title short and sweet and add information, especially if you are coming from outside of the org and haven't filed an issue prior to the PR. In this case I saw you ask in discord, so expected that it might be coming.

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
