### PR TITLE
feat(tauri.js/init): prompt for default values (fix #422/#162)

### LINKED ISSUE #422: Tauri init and first time use
**Is your feature request related to a problem? Please describe.**
When first installing and running tauri init, we should provide an input for a few of the major required settings specifically the path settings and app name. At the completion of the init script, we can note where these config options were stored to make it easier for the user to find them.

Additionally, we can add a `readme.md` in `src-tauri` with the simple instructions for running and point them to our docs for further help. This will give a helping hand to anyone using tauri "indirectly".

### PR DESCRIPTION
**Pull request by nklayman**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes. Issue #422/#162
- [ ] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
`tauri init` will now prompt for the window title, distDir, and devPath via inquirer. The prompts can be skipped if the values are passed via cli arguments. This is a breaking change as the init command requires user input to run. Before merging, are there any other values that should be prompted for? Binary/installer name come to mind but I'm not sure how to configure that.

### CODE REVIEW

**Comment by nothingismagick** [comment]
I don't like the breaking nature of this, and think we should use a default in order to retain current behaviour. One idea might be to also allow them to choose a "pattern" that then sets up their `tauri.config.json` (and potentially their `main.rs`) for e.g. the Kamikaze.

**Comment by lucasfernog** [comment]
Yeah maybe starter kits is the way to go, but this inquirer approach is good for now, just need to lock it with some kind of CLI arg.

**Comment by nklayman** [comment]
I don't like breaking changes either but imo the default should be to prompt for the settings as they are required and are often wrong by default and could leave people very confused.

**Comment by nothingismagick** [comment]
what's the status of this PR? should we merge?

**Comment by nklayman** [comment]
It can be merged, but I want to make sure there aren't any suggestions for other values that should prompted for. It would be nice to be able to prompt for installer/binary name and output dir but I'm not sure if this is possible.

**Comment by nothingismagick** [comment]
Are we still waiting for something here @nklayman ?

**Pull request merged**
