### PR TITLE
feat(tauri-plugin): generate permissions reference markdown file for plugin

### PR DESCRIPTION
**Pull request by lucasfernog**
Since the amount of generated permissions is huge, documenting it at the app-level seems like the best place to do so:

- central place for every available permission
- only lists permissions that are actually available to the app (does not show plugins that are not being compiled)
- autogenerated, no need for us to keep huge lists of permissions for every plugin on the docs website

### CODE REVIEW

**Comment by amrbashir** [comment]
I don't see any value of this tbh, most users will not look into auto-generated files, and they will most definitely search for them on the doc site

**Comment by lucasfernog** [comment]
Documenting all available permissions gets really tricky :|

**Review by amrbashir — DISMISSED** [review]
This is relatively small change and I am fine with it but we still need to document these on the doc site somehow.

**Comment by lucasfernog** [comment]
Maybe we can generate that on the plugin level instead? I know the docs repo has a git submodule for the plugin workspace...

**Comment by amrbashir** [comment]
Yeah sure, we can maybe provide a helper method in `tauri-plugin` crate to facilitate this, it should also be updated with each change to the permissions list.

**Review by amrbashir — APPROVED** [review]

**Pull request merged**
