### PR TITLE
feat(updater): expose builder, allow setting a custom version checker

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
Here is goes 😉: I felt `version_comparator` is a custom `Ord` implementation so I was confused that it didn't return `std::cmp::Ordering`.
`updater_checker` is better, but feels less descriptive and more like it's a callback that is responsible for checking the actual http endpoint.

I would suggest `should_update` instead. It's simple and returning a bool makes a lot of sense from the name alone. 

Edit: We also already use `should_update` as the value name, so why not just make that the function name too?

**Comment by lucasfernog** [comment]
`should_update` feels more like a builder method to set a bool than a closure though.

**Comment by lucasfernog** [comment]
I changed it to `version_checker` recently btw.

**Comment by JonasKruckenberg** [comment]
> I changed it to `version_checker` recently btw.

Ah yeah sorry meant that 😅

**Comment by JonasKruckenberg** [comment]
> `should_update` feels more like a builder method to set a bool than a closure though.

Good point...

How about `should_install_update`?

That way it's clearer that it means the noun update, not the verb.

**Comment by lucasfernog** [comment]
> > `should_update` feels more like a builder method to set a bool than a closure though.
> 
> Good point...
> 
> How about `should_install_update`?

Better than `should_update`. If no one can come up with a better name, let's go with this one.

**Comment by JonasKruckenberg** [comment]
We can also shorten it to `should_install` maybe 🤔 though `should_install_update` is clearer

Edit: I think I prefer `should_install`, since it's already clear that it's about updates from the context (the getter is called `updater()` after all)
Plus `App.updater().should_install_update()` feel unnecessarily redundant. `App.updater().should_install()` just feels nicer to me

**Comment by lucasfernog** [comment]
Good point @JonasKruckenberg

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
