### PR TITLE
feat(cli): Build the CLI for Windows ARM64, closes #7015 (#7098)

### LINKED ISSUE #7015: [feat] Provide @tauri-apps/cli-win32-arm64-msvc NPM package
### Describe the problem

Nowadays I can only manually compile Tauri everytime.

### Describe the solution you'd like

Provide @tauri-apps/cli-win32-arm64-msvc NPM package

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FabianLars**
Port of https://github.com/tauri-apps/tauri/pull/7098

Opening as a draft because i'm not sure how to best combine the feature flags right now...

### CODE REVIEW

**Comment by FabianLars** [comment]
whoops, i actually meant to close/update this PR since i opened it before https://github.com/tauri-apps/tauri/pull/7107 😅

**Comment by FabianLars** [comment]
looks correct to me now. i let you decide if it makes sense to integrate #7017, which splits up the native-tls and native-tls-vendored flags. 
Though i still hope that ring updates before v2 will be stable (unlikely but one can hope) so we can simplify that again 😩

**Comment by lucasfernog** [comment]
I think you linked the wrong PR. Anyway I just want to get this working right now, these feature flags are a mess.

**Comment by FabianLars** [comment]
yeah, swapped the 1 and 0, the one in the first message was correct https://github.com/tauri-apps/tauri/pull/7107

**Comment by lucasfernog** [comment]
Isn't `native-tls` automatically enabled when you enable `native-tls-vendored`? I think it should, that's what all libraries do.

**Comment by FabianLars** [comment]
Nope, that's not what all libraries do, at least not ureq (and iirc atto didn't either), which is why i changed it in dev to behave the same.

**Comment by FabianLars** [comment]
or maybe i'm dumb because ureq doesn't have a vendored feature, but i ended up having to always enable 2 feature flags to not end up with tls errors 🤔 

Edit: Feel free to double check that yourself, all these flags confuse the hell out of me especially when there are 2 or 3 http clients involved

**Comment by lucasfernog** [comment]
We should work on removing attohttpc from dev anyway like you suggested, I think it would benefit the codebase overall.

**Comment by lucasfernog** [comment]
How were you testing this btw @FabianLars ? Build targetting arm on windows?

**Comment by FabianLars** [comment]
Yes, targeting arm to make sure it builds, and targeting x64 with the same flags to make sure i don't get any runtime errors (i have no arm machine to test)

**Comment by lucasfernog** [comment]
I like it this way where you don't need to specify `native-tls,native-tls-vendored` and the -vendored implies the native-tls feature. I can't really compile for arm64 on my VM (stupid Ring?) but it should work the same as the dev stuff you pushed.

**Comment by FabianLars** [comment]
Yeah I agree, i just meant to match what i thought was the default. Let's change it for dev too then :)

If ring still prevents compilation then this PR is kinda useless. Maybe there is another dep that needs disabled default features. I'll take a look at it on my Windows machine in the evening :v:

**Comment by lucasfernog** [comment]
Ahh I see. Gonna see if I can find it.

**Comment by lucasfernog** [comment]
We need some changes on tauri-mobile, I'll work on it.

**Comment by lucasfernog** [comment]
@FabianLars now I think it's ready. I also changed the CI to test arm64 Windows builds since it is quite fragile. Let me know if you see any mistakes.

**Review by lucasfernog — APPROVED** [review]

**Comment by FabianLars** [comment]
Yeah, looks good to me 👍

**Pull request merged**
