### PR TITLE
docs(windows): document required NuGet configuration

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
genuine question out of curiosity, in what circumstances doesn't this happen automatically?
For example i removed this file and everything related (like NuGet repo caches), ran `cargo clean` and `cargo build` and it just re-added the file. Never used NuGet stuff myself other than what tauri/deps use behind the scenes, so no idea how that stuff works, but i never had to do this on any system.

**Review by wusyong — APPROVED** [review]

**Comment by wusyong** [comment]
Maybe set this as optional for those who encounter linking difficulty?

**Comment by lucasfernog** [comment]
> genuine question out of curiosity, in what circumstances doesn't this happen automatically? For example i removed this file and everything related (like NuGet repo caches), ran `cargo clean` and `cargo build` and it just re-added the file. Never used NuGet stuff myself other than what tauri/deps use behind the scenes, so no idea how that stuff works, but i never had to do this on any system.

I have no idea, but it happened to two devs I know.

**Comment by lucasfernog** [comment]
Maybe this would be better inside a FAQ.

**Comment by wusyong** [comment]
> Maybe this would be better inside a FAQ.

Yeah probably better place. Devs with clean install shouldn't have this issue I suppose

**Comment by lucasfernog** [comment]
The FAQ still needs to be hooked on tauri-docs but it's something the community has been requesting for some time.

**Pull request merged**
