### PR TITLE
fix: truncate file when not appending in `writeFile`, closes #7973

### LINKED ISSUE #7973: [bug] `writeTextFile` does not completely overwrite existing file.
### Describe the bug

When using `writeTextFile` to overwrite an existing file, if the new content is shorter than the old content, the file is only partially overwritten.

### Reproduction

```js
import {fs} from "@tauri-apps/api";

await fs.writeTextFile('test.txt', '12345') // file content is now '12345'
await fs.writeTextFile('test.txt', 'abc') // file content is now 'abc45'
```

### Expected behavior

After the second operation, the file content should be 'abc'

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.1 (d5c2e9c34 2023-09-13)
    ✔ Cargo: 1.72.1 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.8.0
    - pnpm: 8.8.0
    - yarn: 3.6.3
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.5.1
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: not installed!
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

I believe `writeFile` and `writeBinaryFile` suffer from the same problem.

### PR DESCRIPTION
**Pull request by zh217**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information
Original issue: https://github.com/tauri-apps/tauri/issues/7973

### CODE REVIEW

**Comment by FabianLars** [comment]
Hey, thanks for contributing! 2 things before we can merge this:
1) I think this can be simplified by just using [`truncate()`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.truncate)
2) We require all commits to be signed, here's a guide on how to set it up: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by zh217** [comment]
Thanks for the suggestion. It's now changed and signed.

**Comment by FabianLars** [comment]
Cool, thanks! One last thing i always forget myself is a changefile like this: <https://github.com/tauri-apps/tauri/blob/dev/.changes/fix-ipc-payload.md> - once that's added we can merge your PR :)

**Review by FabianLars — APPROVED** [review]
Thank you!

**Pull request merged**
