### PR TITLE
Migrating examples to the example repo

### PR DESCRIPTION
**Pull request by tytrdev**
I'm opening this so other can monitor my changes to make sure I'm going about this correctly. Still a WIP.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [X] Refactor
- [X] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by jbolda** [comment]
It seems that import may not have worked. It looks like each example has the full Tauri repo in it.
https://github.com/tauri-apps/examples/tree/feature/import-examples/examples/react/create-react-app/examples/react/next.js

**Comment by jbolda** [comment]
@nothingismagick we should be able to emulate a very similar folder structure by checking out both repos using the new functionality: https://github.com/actions/checkout#checkout-multiple-repos-nested

We will want to get the example repo squared away first before this gets merged in. @tytrdev it may make sense to update the actions in this PR as well.

**Comment by nothingismagick** [comment]
@jbolda - can this be merged now?

**Comment by jbolda** [comment]
I think we should probably update the actions as part of this PR first.

**Comment by jbolda** [comment]
I think the github actions are nearly working, but it needs this to merge first: https://github.com/tauri-apps/examples/pull/7

**Pull request merged**
