### PR TITLE
fix(core): fix deadlock when using resources_table in menu/image/tray plugins

### LINKED ISSUE #9369: [bug] Context menu creation in Javascript is broken
### Describe the bug

It seems the context menu creation from Javascript side is currently broken. The `Promise` returned from `Menu.new()` never resolves. It just hangs forever.

### Reproduction

1. Create the sample app with `--beta`.
2. In the `greet()` function of main.ts, add this line at beginning:
```
    const item = await MenuItem.new({
        text: 'Hello',
        action: () => { console.log('World') },
    })
    Menu.new().then(menu => { menu.append(item) })
```
3. Add import `import { Menu, MenuItem } from '@tauri-apps/api/menu'`.
4. Add capacity "menu:allow-new" and "menu:allow-append".
5. Run the app. Click the greet button. The app hangs. Nothing shows up in the console.

### Expected behavior

Using context menu should not hang the app. It was working before today's update.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.65
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.1
    - npm: 10.2.4
    - bun: 1.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-beta.12
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

Another thing seemingly happens after today's update. Whenever I launch the app in dev mode, a new directory with gibberish name is created in the same directory of the executable (`src-tauri\out\debug`), which houses the EBWebView subdirectory. That directory should be located at `$LOCALAPPDATA/<app_identifier>/`.

### PR DESCRIPTION
**Pull request by amrbashir**
closes #9369

### CODE REVIEW

**Comment by CrendKing** [comment]
That's fast! Thanks!

**Comment by morajabi** [comment]
anything blocking this?

**Comment by FabianLars** [comment]
Whoops, my bad. I thought I approved this already.

**Comment by FabianLars** [comment]
Actually on a second look, do we need to document the required resource table source after the scoped table pr or does that not matter?
(I'm having a rough time getting an overview on my phone rn...)

**Comment by morajabi** [comment]
this prevents us from updating to latest version, that's why I asked <3

**Comment by amrbashir** [comment]
although not needed that much

> Actually on a second look, do we need to document the required resource table source after the scoped table pr or does that not matter?

there is no hard requirement on which resource table is used, it will return an error if can't be found but I updated the documentation to recommend using the webview one

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
