### PR TITLE
Initial support of egui native window

### PR DESCRIPTION
**Pull request by wusyong**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by amrbashir** [comment]
Shouldn't this be a runtime of its own rather than adding it inside `tauri-runtime-wry` ? I mean that's the whole point of the runtime layer .

**Comment by wusyong** [comment]
This isn't a web runtime really. It still uses tao as backend. The purpose of this method is same as `create_tao_window` for the experiment (but for OpenGL).

**Comment by amrbashir** [comment]
> This isn't a web runtime really.

Yeah, I am saying it should have its own runtime -> `tauri-runtime-egui` and depending on the feature flag, tauri will choose the runtime

**Comment by wusyong** [comment]
This is for creating additional windows, not entire application. With `tauri-runtime-egui`, you won't be able to create an egui and a tauri window at the same time.
I do hope we can add this just as a plugin but tauri doesn't expose the same event from tao. And doing so won't be a trivial task.
We are lacking ways to interact with OpenGL so this is the minimum approach to try.

**Comment by amrbashir** [comment]
I see, I guess we can revisit this in tauri v2, once we refactor `tauri::Builder::run()` and expose all events

**Pull request merged**
