### PR TITLE
feat(bundler): display name for bundle

### PR DESCRIPTION
**Pull request by mariotaku**
This PR Is for #8109, #8349 and #8363.

For Linux, productName needs to be converted to lower-kebab-case. To make sure app desktop entry displays user friendly name, `displayName` has been added.

Example:

```json
{
  "productName": "myapp",
  "displayName": "My App"
}
```

### CODE REVIEW

**Comment by FabianLars** [comment]
Hi, thanks for contributing! This is not a full review yet, as i don't have time today to actually try it out but for a start 2 remarks:
1) This may have been added by accident but please remove the deb/rpm changes and open another PR for this if you want to see this in Tauri.
2) in my opinion we shouldn't add this kind of platform specific configs but keep relying on https://tauri.app/v1/api/config#platform-specific-configuration
3) Also, once this is not a draft anymore we'll need a changefile similar to those here: https://github.com/tauri-apps/tauri/tree/dev/.changes

**Comment by mariotaku** [comment]
@FabianLars Hi! Thanks for the quick comment.

1. I'll move deb/rpm changes to another PR. 
2. Sorry, I didn't notice we already have platform specific configuration already, I'll utilize it and add `displayName` only.
3. Sure! I'll be making this change too.

**Comment by mariotaku** [comment]
Done updating the change. Please let me know if there are anything missing :)

**Comment by mariotaku** [comment]
Hi @FabianLars, is it possible to include this change in 2.0 release?

**Comment by FabianLars** [comment]
I hope so, yes. I didn't try it yet but your changes look correct and reasonable as far as i can see.

Paging @amrbashir for a double check on the windows installers

**Comment by xuchaoqian** [comment]
Is it easy to confuse "product name" and "display name"?
How about using "bundle name" as the name for the bundle?

**Comment by mariotaku** [comment]
@xuchaoqian Sounds good too, especially for Linux

**Comment by amrbashir** [comment]
I am not keen on adding another option that is almost identical to `productName`.

#8109 can be fixed by keeping the executable name generated from cargo and avoid renaming it.

#8349 can be fixed by removing the implicit kebab-case conversion and ensure that `productName` is used as is in the generated `.desktop` file.

#8363 can be fixed by modifying the codepage and/or using a Chinese locale.

**Comment by FabianLars** [comment]
sounds good to me too ig 🤷

**Comment by amrbashir** [comment]
cc @lucasfernog

**Comment by lucasfernog** [comment]
I like @amrbashir idea. But we need to at least make a copy of the binary to change its name, otherwise it'll look weird on linux and windows.

If we're going to break the bundler output paths, please do so asap.

**Comment by amrbashir** [comment]
> But we need to at least make a copy of the binary to change its name, otherwise it'll look weird on linux and windows

Could you explain a bit more, not sure if I understand the issue

**Comment by mariotaku** [comment]
@amrbashir Thanks for your input, and I have some ideas about the solutions you've mentioned.

> #8109 can be fixed by keeping the executable name generated from cargo and avoid renaming it.

This sound great, will you make bundler respect binary name defined in `Cargo.toml`? Or I could try making a PR.
 
> #8349 can be fixed by removing the implicit kebab-case conversion and ensure that `productName` is used as is in the generated `.desktop` file.

I'm afraid this will have some issues, because debian package names are having lower-kebab-case. If you override `productName` in `tauri.conf.json`, title in desktop file generated will become lower-kebab-case too.

**Comment by amrbashir** [comment]
> This sound great, will you make bundler respect binary name defined in `Cargo.toml`? Or I could try making a PR.

Feel free to open a PR. The CLI renames the binary after it gets generated by Cargo, we just need to remove that behavior.

> I'm afraid this will have some issues, because debian package names are having lower-kebab-case. If you override `productName` in `tauri.conf.json`, title in desktop file generated will become lower-kebab-case too.

Not sure I quite follow what you mean, but we only need to use kebab-case where required and keep everything else as the normal non-kebab-case productName.

**Comment by mariotaku** [comment]
@amrbashir 


>>     I'm afraid this will have some issues, because debian package names are having lower-kebab-case. If you override productName in tauri.conf.json, title in desktop file generated will become lower-kebab-case too.
> Not sure I quite follow what you mean, but we only need to use kebab-case where required and keep everything else as the normal non-kebab-case productName.

For bundles like `deb`, the name [must be kebab-case](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source). So this is where the conversion required. But this PR was trying to override the automatic conversion when it can't produce desired one. 

For example, when the product name is `webOS Dev Manager`, it will be converted to `web-os-dev-manager` while the desired one would be `webos-dev-manager`, like `OpenDeck` in #8349.

Can this case be covered?

**Comment by amrbashir** [comment]
I believe that could be covered by using a custom `.desktop` template.

**Comment by nekename** [comment]
> For example, when the product name is `webOS Dev Manager`, it will be converted to `web-os-dev-manager` while the desired one would be `webos-dev-manager`, like `OpenDeck` in #8349.

Exactly

**Comment by mariotaku** [comment]
> > For example, when the product name is `webOS Dev Manager`, it will be converted to `web-os-dev-manager` while the desired one would be `webos-dev-manager`, like `OpenDeck` in #8349.
> 
> Exactly

I solved it by doing this:

1. Create `tauri.linux.conf.json` and set `productName` to the one you want (for me, webos-dev-manager`) [example](https://github.com/webosbrew/dev-manager-desktop/blob/e76afaac1a9ecf98aef023aa0e246471de08f810/src-tauri/tauri.linux.conf.json#L2)
2. Create a `.desktop` entry with the display name you want, and configure to make tauri use that. [example](https://github.com/webosbrew/dev-manager-desktop/blob/e76afaac1a9ecf98aef023aa0e246471de08f810/src-tauri/tauri.conf.json#L44)

Not very straightforward but works fine

**Comment by nekename** [comment]
> I solved it by doing this:

Oh, awesome! Do you know if that works on Tauri v1 as well (otherwise I can just https://tryitands.ee)?

Edit: it seems to work! I had to surround `productName` in `package` for it to work in Tauri v1.

**Comment by amrbashir** [comment]
Just a note that we have decided to add `mainBinaryName` option in https://github.com/tauri-apps/tauri/pull/10977 to control the main binary name, this makes `productName` essentially the displayName (which is what it was supposed to) and the new option for main binary name only.

**Pull request closed without merging**
