### PR TITLE
feat(core/webview): add window close function

### PR DESCRIPTION
**Pull request by nklayman**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lucasfernog** [comment]
We also need it on the TS API right?

**Comment by nklayman** [comment]
Oh yeah I was just thinking about from the rust side, but that's a good idea.

**Comment by lucasfernog** [comment]
Hmm yeah maybe on the JS layer they can just use `window.close` - unless it makes any difference

**Comment by nklayman** [comment]
`window.close()` doesn't do anything actually

**Comment by lucasfernog** [comment]
We should probably override it then.

**Comment by nklayman** [comment]
That should probably be done by wry, correct?

**Comment by lucasfernog** [comment]
Yeah maybe.

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
