### PR TITLE
fix: MacOS Frameworks not signed, closes #7690 and #7710

### LINKED ISSUE #7690: [bug] MacOS Codesign doesn't handle frameworks
### Describe the bug

I'm developing an application on MacOS that uses a 3rd Party Framework that I package with my application. When code signing and then distributing the app, I get crash reports on boot regarding the Framework and it having discrepancies in the team id 

```
Not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs
```

During my testing and research today, I found that Apple recommends signing included frameworks along with your app itself. So I tried this on the `.app` file, first signing the internal Framework and then signing the overall App itself and it cleared up the issue.

I'm guessing this is something that needs to be added to the bundler?

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.15.0
    - yarn: 1.22.19
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.4.1 (no manifest)
    - tauri-build [RUST]: 1.4.0 (no manifest)
    - wry [RUST]: 0.24.3 (no manifest)
    - tao [RUST]: 0.16.2 (no manifest)
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: style-src 'unsafe-inline' 'self'; default-src 'self'; img-src 'self' asset: https://asset.localhost; connect-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:3010/
    - framework: React
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tr3ysmith**
### What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?
- [ ] Yes, and the changes were approved in issue #___
- [X] No (however it does fix an issue I found with notarytool, which now seems to require a team-id. I added a new env variable called APPLE_TEAM_ID for notarizing

### Checklist
- [X] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by tr3ysmith** [comment]
https://github.com/tauri-apps/tauri/issues/7690

**Comment by tr3ysmith** [comment]
So this morning, I came in to build my app, and it failed signing... So I'm looking into this further, I've also submitted a support ticket with Apple to get more clarity

**Comment by tr3ysmith** [comment]
Linking in this article, looks like Apple codesign can fail if extra attributes exist on files inside the bundle....
https://developer.apple.com/library/archive/qa/qa1940/_index.html

Wondering if we should add the command to remove all extra attributes on the app bundle before signing?

**Comment by tr3ysmith** [comment]
Added a function to strip extra attributes and it seems to have fixed an error I saw this morning

**Comment by tr3ysmith** [comment]
**FROM APPLE**

When embedding frameworks there are two important things to note:

* You must copy the framework in a way that preserves symlinks.  I often see problems where folks copy a framework using `cp -r`, which expands the symlinks, which effectively breaks the code.  I generally recommend copying code with `ditto`.

* The notary service requires that all code be signed with a valid Developer ID, so it’s possible to build an app from components signed by different developers.  My general advice, however, is that you re-sign any nested code with your Developer ID.  Sign each code item separately, from the inside out.

**Comment by tr3ysmith** [comment]
#7710

**Comment by tr3ysmith** [comment]
So in testing, I think this is actually all good to go for now. I think we need to ultimately address assigning specific entitlement.plist files to each included binary in the app, both sidecar and frameworks. Apple recommends not using the same plist file for everything as it could break stuff. We should probably also look at removing the --deep argument on the codesign tool in the future and manually signing stuff

**Comment by tr3ysmith** [comment]
@FabianLars if this pull request gets approved, we'll need to add APPLE_TEAM_ID as an argument to the GitHub action once its released, since it seems like notarytool requires it now.

**Comment by tr3ysmith** [comment]
@FabianLars I've added signing for sidecar binaries, but I haven't been able to fully test it as I don't have a sidecar project setup. I've also removed --deep in this latest commit

**Comment by lucasfernog** [comment]
@tr3ysmith I see you added a fix for 3 separate issues in this PR (and you also added a breaking change with the `APPLE_TEAM_ID` environment variable). Can you break it into 3 different PRs? it'll also help our auditing team.

Thank you :heart:

**Comment by lucasfernog** [comment]
> @FabianLars if this pull request gets approved, we'll need to add APPLE_TEAM_ID as an argument to the GitHub action once its released, since it seems like notarytool requires it now.

From my tests the team id isn't required. We also already merged notarytool usage into 1.x.

**Comment by tr3ysmith** [comment]
@lucasfernog ah sounds good, so I can adjust this to allow team id but not require it.

I'll close this PR and open 3 separate ones.

**Comment by tr3ysmith** [comment]
#7773 - add rpath
#7774 - fix codesigning
#7775 - Apple Team ID

**Pull request closed without merging**
