### PR TITLE
feat(tauri): #1977 add `async_runtime::handle` for access to async runtime

### PR DESCRIPTION
**Pull request by ravern**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by chippers** [comment]
if this is added, it should be behind a **non-default** `async-runtime-tokio` feature flag to prevent having a dependency re-export which would prevent switching runtimes/apis in the future

**Comment by lucasfernog** [comment]
We should create a wrapper Handle too, so we do not return a tokio type directly.

**Comment by ravern** [comment]
> We should create a wrapper Handle too, so we do not return a tokio type directly.

If this was to make it easier to rework the underlying runtime in the future, perhaps a trait would be better?

```rust
trait RuntimeHandle {
  fn spawn(...);
  fn block_on(...);
}

fn handle() -> impl RuntimeHandle { ... }
```

**Comment by lucasfernog** [comment]
Yeah a trait works too.

**Comment by lucasfernog** [comment]
See #2399.

**Pull request closed without merging**
