### PR TITLE
fix(cli): dev command stderr text overflow on Windows, closes #3995

### LINKED ISSUE #3995: [bug] cargo's terminal output overflows
### Describe the bug

Tested in cmd and powershell, both inside and outside of the MS Terminal app.
image

### Reproduction

1. run `cargo clean` in your src-tauri dir.
2. run `tauri dev`

### Expected behavior

_No response_

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 100.0.1185.50
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 6.32.10
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

Can you check this one @FabianLars ? I'm not sure because the issue isn't happening to me anymore, even without the change :|

### CODE REVIEW

**Comment by FabianLars** [comment]
Nope, still the same

**Comment by lucasfernog** [comment]
@FabianLars it should work now, though I fear it only hides the issue (probably in Cargo?) by limiting the progress bar to width 60.

**Comment by FabianLars** [comment]
Yeah it works. It's looks kinda weird, because it doesn't have enough space to write the currently compiling crates, but i'd rather see this than this overflow mess 👍

**Comment by lucasfernog** [comment]
Yeah unfortunately even `80` as width breaks it :/

**Pull request merged**
