### PR TITLE
fix(core): Mark `identifier` as a required field.

### PR DESCRIPTION
**Pull request by FabianLars**
Noticed in https://discord.com/channels/616186924390023171/1276353618093674518 where only the .msi build failed to build even though bundle.publisher was set. If both publisher and identifier are set it correctly uses publisher and since identifier is required with this pr i don't really care about that potential issue.

### CODE REVIEW

**Review by lucasfernog — APPROVED** [review]
ohhhhh i didn't even know about this one!

**Comment by Legend-Master** [comment]
This change itself has nothing wrong, but now files like `tauri.windows.conf.json` that's supposed to be merged into the main config file will get a `Missing property "identifier".` warning which might cause confusions

**Comment by FabianLars** [comment]
Shit forgot to mention that. 😳

but idk I'd rather have it required in the Schema for more tools to pick up the reqs than having some custom validation that only triggers on build.

**Comment by Legend-Master** [comment]
Maybe generate another schema file without the requirement?

**Pull request merged**
