### PR TITLE
feat(tauri) add global shortcut API

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ken0x0a** [comment]
Is there any reason for that this is not merged for a while?

Global shortcut API is great, isn't it?

**Comment by lucasfernog** [comment]
We need macOS support to merge this, but `hotkey` only supports Linux and Windows :(

**Comment by ken0x0a** [comment]
Is this help for this to be merged?
https://github.com/gamebooster/soundboard/blob/master/extern/hotkey-rs/src/macos.rs

**Comment by lucasfernog** [comment]
What?? How did you find this gem??? You're a genius. I'm definetely going to find some time to try it, maybe we can publish it next week. Awesome work!

**Comment by lucasfernog** [comment]
By the way if you want to contribute, you could see if the original hotkey-rs repo would accept a PR with that code or push that to a repo and see if it works (if you have a macOS).

**Comment by ken0x0a** [comment]
Thank you for awesome project!!

Actually, I was thinking about it, but I quit as I've never read "C" and,
now I'm learning Rust. So it's too much for me 😊

I'm looking forward to seeing this to be merged.
And I cannot wait "Copy & Paste" feature, and using Tauri 😆

**Comment by lucasfernog** [comment]
No problem. Enjoy the learning, it's difficult but rewarding :) copy and paste would be the next step. Ping us on Discord in case you need anything.

**Comment by lucasfernog** [comment]
My first experiment with Soundboard's hotkey-rs fork wasn't successful, seems like it doesn't work on latest macOS version :(

**Comment by nothingismagick** [comment]
Regarding copy/paste:

https://github.com/webview/webview/pull/405

That will land imminently, and although it's slightly different than this concern wanted you to know about it.

**Comment by lucasfernog** [comment]
Hmm I was thinking about writing a Rust implementation but seems like a waste of time with that feature.

**Comment by futurist** [comment]
+1 for this PR, urgently need it!

**Comment by ken0x0a** [comment]
I could "copy & paste" on macOS, when I register main menus for ":copy: & ":paste".

Is it possible to do "copy & paste" already on Linux & Windows?
Is https://github.com/webview/webview/issues/403 work on all platform?

**Comment by lucasfernog** [comment]
I believe WRY makes this feature possible. I tested it again and it seems like it wasn't working on macOS due to the lack of a winit window. I'll try to get it done next week.

**Comment by lucasfernog** [comment]
I'm going to close this PR and open another one - too many conflicts :)

**Pull request closed without merging**
