### PR TITLE
[feat] add dialog title option. closes #3232

### LINKED ISSUE #3232: [feat] Setting title for dialog options
### Describe the problem

I built an app that on startup connects to a database file (sqlite) on the internal network.

Without this database the app makes no sense.

The app knows the usual path to the database. Also, the user can choose an appropriate database file.

When the app starts up it looks for the last choosen database file. If it does not find it, it opens a dialog to let the user choose one.

As I can't set the title of the open dialog it is titled `Open`. This is not informative. The user is left to wonder what the app wants him/her to open. I want it to say `Choose the database file`.

The app was migrated from electron where the title of an open and save dialog can be set.

This feature would be useful in tauri too.

### Describe the solution you'd like

Add the ability to set a title in [the dialog options](https://tauri.studio/en/docs/api/js/interfaces/dialog.opendialogoptions/).

### Alternatives considered

I will probably have to open a ui dialog in the app that tells the user that after closing it he/she will be presented with a dialog to choose the appropriate database file.

This seems clunky. And is more work.

### PR DESCRIPTION
**Pull request by JonasKruckenberg**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
I have absolutely no idea why those checks are failing, can't reproduce the errors locally even with the flags we use in CI

**Comment by FabianLars** [comment]
Yeah the CI is somewhat weird the last couple of days/weeks :/

**Comment by JonasKruckenberg** [comment]
As far as I can see none of them are related to this PR though. @FabianLars your on windows right? Can you test that the title shows up in the `api` example? On macos only the save dialog has a configurable title sadly

**Comment by FabianLars** [comment]
might take a while, can't make it compile rn lol

**Comment by JonasKruckenberg** [comment]
No worries! I you need to make changes to this branch feel free

**Review by FabianLars — APPROVED** [review]
works on windows (rust & js) 👍

**Comment by JonasKruckenberg** [comment]
Thanks for checking 🙏🏻

**Comment by JonasKruckenberg** [comment]
Oh no that was premature

**Comment by barbalex** [comment]
I just tested it. Worked fine for me on windows in open and save dialog.

**Pull request merged**
