### PR TITLE
build(task-runner): add self-documented task runner

### PR DESCRIPTION
**Pull request by DrSensor**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [x] Other, please describe: developer experience for contributor or maintainer

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
As a new/first contributor, I have difficulty to check the small changes that I made is correct, especially when I want to check if it works on the [examples repo](https://github.com/tauri-apps/examples). I'm choosing [mask](https://github.com/jakedeichert/mask) because it's markdown which can be used as some sort of recipe. (also I'm more familiar with `mask` codebase)
tauri-mask-run-example

### CODE REVIEW

**Comment by lucasfernog** [comment]
Wow this is so cool.

Btw do we have a contribution guide?

**Comment by nothingismagick** [comment]
@lucasfernog => https://github.com/tauri-apps/tauri/wiki/14.-Contributor-Introduction

**Comment by jbolda** [comment]
@DrSensor very cool! I have been working on a good workflow using yarn workspaces for the examples, but that won't cover the rust based examples. This looks like it has the capability though which is great. It appears that this may not work on Windows though which is unfortunate 😣.

My other thought is that I wonder if this is best added to the examples repo?

**Comment by jbolda** [comment]
I was actually thinking _only_ have the maskfile in https://github.com/tauri-apps/examples as the functions relate specifically to them. I guess my personal opinion regarding the examples is that they serve strictly as test grounds and the expectation is that they won't be cloned to start a project. Instead we push towards using the CLI to start a project. What do others think? It seems to always be an ongoing discussion.

The paths certainly could be an issue on Windows, but if it works in bash and WSL that's better than nothing.

**Comment by nothingismagick** [comment]
@jbolda - can't we do both?

**Comment by jbolda** [comment]
@nothingismagick If that is what you would like to do, it's not unreasonable. We would have to maintain it in both places, but there are worse situations.

**Comment by tensor-programming** [comment]
Ill look into making it work on windows but bash and wsl only support is a bit unacceptable. Most windows devs don't use either or would rather not use either.

**Comment by nothingismagick** [comment]
@tensor-programming - with your powershell amendment this could be approved?

**Comment by tensor-programming** [comment]
its being looked at here: https://github.com/jakedeichert/mask/pull/45

They said they would review it next week.

**Comment by lucasfernog** [comment]
can this be merged already?

**Comment by jbolda** [comment]
We were waiting on the upstream next version with @tensor-programming changes.

**Comment by tensor-programming** [comment]
This can likely be merged, the changes where made a few weeks ago.

**Comment by jbolda** [comment]
Thanks @DrSensor for taking care of this!

**Pull request merged**
