### PR TITLE
ci: Fix v1 docs update trigger

### PR DESCRIPTION
**Pull request by FabianLars**
In the docs repo I'd prefer to keep v1 workflows in the v1 branch so the old repository_dispatch doesn't work anymore. With the gh cli we can trigger the normal workflow_dispatch though.

I have a feeling this may not work on the first try so we need to monitor this on the next v1 release :)

### CODE REVIEW

**Review by amrbashir — DISMISSED** [review]

**Comment by amrbashir** [comment]
shouldn't this PR target `1.x` branch?

**Comment by FabianLars** [comment]
Probably maybe perhaps - github's UI always directed me to the dev branch so i was utterly confused. But you're right, the msrv prs also were against the 1.x branch.

**Comment by FabianLars** [comment]
sadge

**Comment by FabianLars** [comment]
sadge

**Comment by FabianLars** [comment]
grafik
chill github...

**Pull request closed without merging**
