### PR TITLE
refactor(example): simplify streaming example by using asset protocol

### PR DESCRIPTION
**Pull request by keiya01**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by amrbashir** [comment]
The streaming example is an example of sending only the bytes requested in the range header while the `asset` protocol will send the whole file, so you can't simply replace streaming with `asset` protocol.

**Comment by keiya01** [comment]
I think asset protocol has feature to use range header too :eyes:
https://github.com/tauri-apps/tauri/blob/c82b4761e1660592472dc55308ad69d9efc5855b/core/tauri/src/manager.rs#L545

**Comment by amrbashir** [comment]
Oh, good to know that, thanks.

Still, since it is a still an example about streaming, it should show a manual implementation that can be a reference to others who want to implement their own.

**Comment by keiya01** [comment]
Maybe we can also export function to process the range header.
What do you think about it?

**Comment by amrbashir** [comment]
you should ask @lucasfernog

**Comment by keiya01** [comment]
@lucasfernog 
I think we can export a function to process the range header.
What do you think about it?
This is because currently we have some large boilerplate to process the range header.

**Comment by lucasfernog** [comment]
We can't really expose a range parser because we didn't even implement multiple ranges yet.

**Comment by FabianLars** [comment]
I actually interpreted this example as an example for the `register_uri_scheme_protocol` function with streaming just being a good way to showcase it.
I somewhat regularly forward people to the example (for the custom protocol), so i'd rather not remove it like this.

**Comment by keiya01** [comment]
I understood.
Thank you for your reply.

**Pull request closed without merging**
