### PR TITLE
fix(tauri): docs.rs build error

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
Can we somehow remove ayatana-tray from the default features? disabling it is kinda ugly rn

**Comment by lucasfernog** [comment]
And force everyone to pick one?

**Comment by FabianLars** [comment]
yeah i don't know, it's tricky right now. For me on fedora i have to disable the default features and then add 4 feature flags (`"wry", "compression", "objc-exception", "gtk-tray"`) to make it work again.

As a side note we need to update the docs for that asap too (if we leave it as-is).

**Comment by lucasfernog** [comment]
Disabling it is not that bad:

```toml
[dependencies]
tauri = { path = "../../../core/tauri", default-features = false, features = ["wry", "compression", "objc-exception"] }

[features]
default = [ "custom-protocol", "tauri/ayatana-tray" ]
custom-protocol = [ "tauri/custom-protocol" ]
gtk-tray = [ "tauri/gtk-tray" ]
```

**Comment by lucasfernog** [comment]
I thought we agreed on having ayatana-tray as a default feature since libappindicator isn't supported on newer distro releases (debian I think).

**Comment by FabianLars** [comment]
Well maybe my actual problem here is that the tray is generally enabled by default because it never was before (it was only enabled if you had a systray config in tauri.conf.json).

**Comment by lucasfernog** [comment]
The tray isn't enabled by default. Can you share what's happening in your end?

**Comment by FabianLars** [comment]
i get a cc linker error because ayatana is a default feature even if i don't have a systemtray configured (ayatana is also listed in the lockfile unless i disable the default features).

you ofc still can't use the actual systray apis because they are behind the system-tray feature flag.

**Comment by lucasfernog** [comment]
Ahh you're right :/ I don't think we can fix it.

**Comment by lucasfernog** [comment]
Unless we force the user to pick the feature.

**Comment by FabianLars** [comment]
Yeah i only see 3 shitty alternatives rn:
- like you said, force the user
- somehow detect the correct one in the cli (either by checking for fedora or for the lib if that's possible)
- completely drop libappindicator 🤷 

So i guess we leave it as-is for v1 and maybe consider dropping it for v2 since we need to look into changing our build tooling for new webkitgtk versions anyway where we probably end up with custom docker containers or something...

linux really likes to give headaches

**Comment by lucasfernog** [comment]
Maybe we should leave the choice to the user. Currently everyone will need to have one of the libs installed in their system, even if not using the system tray feature :/ (and we also get easier toggling between gtk/ayatana since no one will need to disable default-features).

**Pull request merged**
