### PR TITLE
add "webview:allow-internal-toggle-devtools" to default.json

### PR DESCRIPTION
**Pull request by Fake-User**
developers should be able to open dev tools in the default project

### CODE REVIEW

**Comment by Legend-Master** [comment]
Isn't it included in `webview:default`?

**Comment by FabianLars** [comment]
yes it is

**Comment by FabianLars** [comment]
@Fake-User can you tell us a bit more about the issue you were facing? Can you check whether you had `webview:default` enabled?

**Comment by Fake-User** [comment]
@FabianLars testing with a fresh Tauri v2 project [ bun create tauri-app --beta ] on macOS Sonoma 14.5.

The "webview:default" permission is in the default.json, but the shortcuts for [opening the webview console](https://v2.tauri.app/develop/debug/#webview-console) do not work without adding the "webview:allow-internal-toggle-devtools" permission.

**Comment by Legend-Master** [comment]
~~ah, I see when I press ctrl + shift + i on windows, the devtools does show up but with `VM12:263  Uncaught (in promise) Command plugin:webview|internal_toggle_devtools not allowed by ACL` logged to the console, probably a bug~~ never mind, just realized the api example doesn't have `webview:default` in the allow list, adding it fixed it

I can't reproduce this on Windows at least

**Comment by Fake-User** [comment]
I just tested on a coworkers m2 mbp, so there is definitely an issue on macOS.
additionally [ cmd opt i ] wont close the web view console,
even with this permission enabled : /

**Comment by lucasfernog** [comment]
Just tested it on macOS and it works after adding `webview:default` (without this change).

**Comment by lucasfernog** [comment]
btw that API only works on debug builds (or release built with --features tauri/devtools)

**Comment by FabianLars** [comment]
Works on my macbook without this pr too 🤔

**Pull request closed without merging**
