### PR TITLE
Make sure custom protocol is handled as secure context on macOS

### LINKED ISSUE #1550: Treat macOS custom protocol as https for WebRTC
**Describe the bug**
macOS custom protocol should be treated as HTTPS.

**To Reproduce**
N/A

**Expected behavior**
WebRTC should be enabled on custom protocol when permissions are granted.

**Additional context**
Linked with https://github.com/tauri-apps/wry/issues/85#issuecomment-823499749

`localhost` should be used as a custom protocol host in macOS. Instead of using `tauri://` we should use `tauri://localhost/` as a base.

### PR DESCRIPTION
**Pull request by lemarier**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

**Other information:**

Do not seem to affect other platforms need to test on Windows and Linux to be sure it didn’t break anything.

Fix #1550
Related to https://github.com/tauri-apps/wry/issues/85

### Without the fix:
Screen Shot 2021-04-20 at 3 11 15 PM

***

### With the fix
Screen Shot 2021-04-20 at 3 10 14 PM

### CODE REVIEW

**Review by nothingismagick — APPROVED** [review]
If there were a flair possible for this kind of PR, then I would grant it legendary status that is literally a game changer. Thanks man. I owe you a caipi. On the Seychelles

**Comment by lucasfernog** [comment]
I'm checking how local storage behaves with this solution. I think the webview caches it based on the url :/

**Comment by lemarier** [comment]
> I'm checking how local storage behaves with this solution. I think the webview caches it based on the url :/

maybe we could make sure local storage use `app` and not `tauri-shared` directory for storage.

**Comment by lucasfernog** [comment]
> > I'm checking how local storage behaves with this solution. I think the webview caches it based on the url :/
> 
> maybe we could make sure local storage use `app` and not `tauri-shared` directory for storage.

That would be great

**Comment by lemarier** [comment]
> That would be great

### macOS

It's stored inside `~/Library/WebKit` and uses the `package.id`

Screen Shot 2021-04-20 at 4 33 59 PM

### Windows

We already use [with_user_data_folder](https://github.com/tauri-apps/wry/pull/120) so not a problem

### Linux

Need to check this out

**Comment by lucasfernog** [comment]
Linux might need this: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebsiteDataManager.html#WebKitWebsiteDataManager--local-storage-directory

**Comment by lucasfernog** [comment]
webkit stores localstorage under `$HOME/.local/share/webkitgtk/localstorage`, so we do need to change it. I'll PR wry.

**Comment by lucasfernog** [comment]
Unfortunately `navigator.mediaDevices` is still undefined on Linux :( we probably need to tweak something on the wry end.

**Comment by lemarier** [comment]
> Unfortunately `navigator.mediaDevices` is still undefined on Linux :( we probably need to tweak something on the wry end.

ok I'll try to make some tests to see what we can do

**Comment by lucasfernog** [comment]
Since this is a macOS PR i'll merge it.

**Comment by wusyong** [comment]
I think we haven't enabled it yet but the method/signal should be here:
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-permission-request

**Pull request merged**
