### PR TITLE
feat: add `title` getter on window, closes #5023

### LINKED ISSUE #5023: [feat] Make Window Title Available in appWindow Instance
### Describe the problem

It's tricky when making custom title bars for a window—or trying to update the window title with something based on the current title—to actually pin down in code what the current title is.

### Describe the solution you'd like

On the `appWindow` level, we have the ability to call `appWindow.setTitle("...")`. It would be good if we could get a reference to the current title here as well. A property of `appWindow.title` would probably be best, but exposing it through `appWindow.getTitle()` would also work fine.

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by lucasfernog — DISMISSED** [review]

**Review by lucasfernog — APPROVED** [review]

**Comment by elibroftw** [comment]
When will this be in production? I'm working on a custom titlebar and this is the second last piece of perfection.
image
Also how do I disable the native title bar? I have decorations set to false.

**Comment by elibroftw** [comment]
image
```js
appWindow.title().then(title => {
      if (windowTitle !== title) setWindowTitle(title);
    });
```
image

**Comment by elibroftw** [comment]
image

**Comment by elibroftw** [comment]
nvm just have to upgrade cargo most likely,

**Comment by elibroftw** [comment]
I updated cargo.toml, and still same error. Does it work for you guys?

**Comment by elibroftw** [comment]
Seems like the other plugins like tauri-plugin-window-state and tauri-plugin-store and tauri-plugin-single-instance depend on 1.2.5?

Had to set `tauri = { version = "1.3",`

**Comment by FabianLars** [comment]
> Seems like the other plugins like tauri-plugin-window-state and tauri-plugin-store and tauri-plugin-single-instance depend on 1.2.5?

Nope, they only [specify `"1"`](https://github.com/tauri-apps/plugins-workspace/blob/v1/Cargo.toml#L8), so if we ignore the fact that some plugins use apis introduced in 1.1 and 1.2 the plugins don't care about the minor version and a simple `cargo update` is _supposed_ to update it (adding 1.3 in your cargo.toml file is basically the same in this context since it tells cargo to upgrade to at least 1.3)

**Pull request merged**
