### PR TITLE
added ARCHITECTURE to update-docs workflow, fixes #2088

### LINKED ISSUE #2088: [docs] Add ARCHITECTURE doc to update-docs workflow for website
> @Laegel ARCHITECTURE doc has been recently created, the idea was to copy it on the update-docs workflow so it appears in the website. Totally forgot that. :smile:

### PR DESCRIPTION
**Pull request by facklambda**
Fixes https://github.com/tauri-apps/tauri/issues/2088

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: modifications to update-docs.yml workflow that publishes docs

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by facklambda** [comment]
~~Sorry, I just realized I neglected to replace many more references to this file in other files, please ignore this PR until I've got that fixed.~~

Disregard previous message, it appears those references were all readme files that don't get copied over to the tauri-docs repo. I over-zealously committed those changes before checking.

**Comment by amrbashir** [comment]
Can you please also apply these changes to the update-docs job in covector workflow ?

Also, I don't think `ARCHITECTURE.md` should be in the getting-started section but I also don't know where it should go.

**Comment by facklambda** [comment]
Sure thing. I'll see how to modify the other workflow.

I wasn't sure which filepath to give the file, so I just threw it in there since getting-started folder held the only other doc that linked to the architecture doc. I assume it could be placed in the `/docs/about` directory, it may fit in there better.

**Comment by facklambda** [comment]
This should be ready for review now.

**Review by lucasfernog — APPROVED** [review]

**Comment by lucasfernog** [comment]
Thanks!

**Pull request merged**
