### PR TITLE
docs(various): Fix Typos

### PR DESCRIPTION
**Pull request by ryanrussell**
Signed-off-by: r <ryanrussell@users.noreply.github.com>

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by JonasKruckenberg — DISMISSED** [review]

**Comment by ryanrussell** [comment]
@JonasKruckenberg rebase with signoff complete. Please Let me know if it isn't correct on your side.

**Comment by JonasKruckenberg** [comment]
> @JonasKruckenberg rebase with signoff complete. Please Let me know if it isn't correct on your side.

It doesn't show the commit as verified, maybe you need to tell Github about your signing key?

**Comment by ryanrussell** [comment]
> > @JonasKruckenberg rebase with signoff complete. Please Let me know if it isn't correct on your side.
> 
> It doesn't show the commit as verified, maybe you need to tell Github about your signing key?

image

This is what it shows on my end. Could you possibly show me what it's showing you that needs completed?

Apologies for the headache

**Comment by JonasKruckenberg** [comment]
For reference this is what a verified commit shows up as on GitHub image

**Comment by ryanrussell** [comment]
@JonasKruckenberg 

Sorry about that! All done, thanks for the guidance.

image

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Yes! Thank you!

**Pull request merged**
