### PR TITLE
feat(ipc): enhance request URL checks, update wry, refactor file drop

### LINKED ISSUE #8156: [feat] continually raising `tauri://file-drop-hover` event and providing current cursor position
### Describe the problem

i am working on an app which is available to highlight some specified html elements while dragging & dropping files (and i need the absolute file path). But i found that `tauri://file-drop-hover` event only happens once when moving file from outside into inside of the window, and did not raise again while moving inside the winodow, Is it possible to continually raise`tauri://file-drop-hover` and tell me the newly cursor position?

BTW: I need the absolute path of the dropped file, it is not a solution to disable `fileDropEnabled` since the chromium native drag & drop feature does not giving me that. or maybe there is some other solution?

### Describe the solution you'd like

continually raising `tauri://file-drop-hover` and providing current cursor position

### Alternatives considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #9286: [bug] Child window failed to show if main window is not visible initially hidden
### Describe the bug

In the tauri.config.json file, if the visible attribute is set to false, and subsequently, the window is displayed using the show() method within the setup() hook, calling a Tauri command to create a child window results in the child window appearing and disappearing automatically.

The child window shows normally if visible is set to true for mainwindow.

Part of tauri.config.json is given below:
```
"app": {"windows": [
      {
        "title": "childwindow-test",
        "width": 800,
        "height": 600,
        "visible": false
      }
    ],
    "security": {
      "csp": null
    }
  },
```

In main.rs file:
```
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use tauri::{AppHandle, Manager};

#[tauri::command]
async fn open_docs(handle: tauri::AppHandle) {
  let docs_window = tauri::WebviewWindowBuilder::new(
    &handle,
    "external", /* the unique window label */
    tauri::WebviewUrl::External("https://tauri.app/".parse().unwrap())
  ).build().unwrap();
}

fn main() {
    tauri::Builder::default()
        .setup(|app|{
            let mainwindow = app.get_webview_window("main").unwrap();
            mainwindow.show();
            Ok(())
        })
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![open_docs])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

In Angular code, i invoke the command using:
```
import { invoke } from "@tauri-apps/api/core";
async openWindow() {
    await invoke("open_docs").then(()=>{
        console.log("Window Created");
    });
}
```

### Reproduction

To reproduce the bug, follow these steps:

- Set `visible` to false in **tauri.config.json**
- Show the main window again using `show()` method from **WebviewWindow**
- Create a tauri command to create a child window.
- Call the tauri command from the front end.

Sample project to reproduce the issue : https://github.com/selastingeorge/childwindow-test
Example code taken from  (Modified for Tauri v2 support): https://tauri.app/v1/guides/features/multiwindow/

### Expected behavior

The child window should be displayed along with main window.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 122.0.2365.92
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.0 (aedd173a2 2024-03-17)
    ✔ cargo: 1.77.0 (3fe68eabf 2024-02-29)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.13
    - tauri-build [RUST]: 2.0.0-beta.10
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.2
    - @tauri-apps/api [NPM]: 2.0.0-beta.6
    - @tauri-apps/cli [NPM]: 2.0.0-beta.11

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist/childwindow-test/browser
    - devUrl: http://localhost:1420/
    - framework: Angular
    - bundler: Webpack
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lucasfernog**
This PR leverages the upcoming [wry IPC refactor](https://github.com/tauri-apps/wry/pull/1183) that exposes the request frame URI on Windows, macOS and iOS (and fallbacks to the main frame URL on unsupported platforms - Linux and Android) along with using the Origin header when the custom-protocol-based IPC is used to determine the request URL instead of using `Webview::url` which only returns the main frame URL. This enhances the check for remote IPC access especially when an iframe is used.

### CODE REVIEW

**Comment by lucasfernog** [comment]
Needs the next wry release.

**Comment by lucasfernog** [comment]
Updated to wry 0.38 which also requires a small file drop event refactor.

**Comment by FabianLars** [comment]
With the update to the new wry version i'd like to mention https://github.com/tauri-apps/tauri/issues/9199. I did not have a chance to test this PR yet though.

**Comment by lucasfernog** [comment]
well at least multiwindow is already broken (and now it at least opens the windows properly)

**Comment by FabianLars** [comment]
The difference is that before there was a _chance_ of it crashing (for most apps a pretty small chance I'd say). Now it _always_ crashes :/

If we still want to ship it asap then I'd recommend to release a temporary wry version with the workaround I added until Amr is back. It disables something that wasn't there before the refactor so I hope it's not too bad to disable it.

**Comment by lucasfernog** [comment]
it's ok, I think this can wait (I'll forget about it so my anxiety isn't triggered :joy: )

**Comment by lucasfernog** [comment]
@amr-crabnebula can you review this one? there's also a possible blocker in the Windows issue :(

**Comment by amrbashir** [comment]
updated this PR to latest `wry`, just waiting on a new release of `wry`

**Comment by Jhkier** [comment]
Hi - any timeline for this merge?

**Comment by FabianLars** [comment]
No ETA. Shouldn't take too long though since the blocker was resolved 🤷

**Review by amrbashir — DISMISSED** [review]

**Review by amrbashir — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]

**Pull request merged**
