### PR TITLE
refactor(cta): use `commander` instead of `minimst`

### PR DESCRIPTION
**Pull request by amrbashir**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding Issue #___
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [X] No

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

`commander` is more robust than `minimst`, two main features I appreciate is:
1. auto-generated help messages (kinda)
2. validation of values passed to options

### CODE REVIEW

**Comment by amrbashir** [comment]
alright, checks have passed, I guess this PR is ready to go

**Review by nothingismagick — APPROVED** [review]
I will approve this, but would really like to recommend that you take the time to fill out the template of the PR and give non-informed readers (aka those not reading every channel on discord) justification for replacing functionality. This is also useful for posterity.

**Comment by amrbashir** [comment]
yeah that's totally my bad, I think I forgot

**Comment by amrbashir** [comment]
I marked this as a draft as I think I still need to do some changes to this PR before merge.

**Comment by amrbashir** [comment]
alright this is ready, but probably need to be merged after the audit as it introduces a new dependency.

**Pull request merged**
