### PR TITLE
fix: codesign doesn't sign frameworks or sidecar, closes #7690

### LINKED ISSUE #7690: [bug] MacOS Codesign doesn't handle frameworks
### Describe the bug

I'm developing an application on MacOS that uses a 3rd Party Framework that I package with my application. When code signing and then distributing the app, I get crash reports on boot regarding the Framework and it having discrepancies in the team id 

```
Not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs
```

During my testing and research today, I found that Apple recommends signing included frameworks along with your app itself. So I tried this on the `.app` file, first signing the internal Framework and then signing the overall App itself and it cleared up the issue.

I'm guessing this is something that needs to be added to the bundler?

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.15.0
    - yarn: 1.22.19
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.4.1 (no manifest)
    - tauri-build [RUST]: 1.4.0 (no manifest)
    - wry [RUST]: 0.24.3 (no manifest)
    - tao [RUST]: 0.16.2 (no manifest)
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: style-src 'unsafe-inline' 'self'; default-src 'self'; img-src 'self' asset: https://asset.localhost; connect-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:3010/
    - framework: React
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tr3ysmith**
### What kind of change does this PR introduce?
Codesigning on Mac requires Frameworks and embedded binaries to be signed from the inside out, this change removes the --deep command on the code signing and individually signs sidecar and frameworks, then the app package

- [X] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [X ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
#7690

### CODE REVIEW

**Review by afonsojramos — APPROVED** [review]

**Comment by lucasfernog** [comment]
@tr3ysmith I pushed some changes and it looks nice, but I can't get the framework signature to be approved by the Apple notarization. I'm using our updater integration test to validate it, if you want to run it too, simply configure your signing/notarization environment variables and run `cargo test --test '*' -- --ignored` in the root of the repository.

`notarytool log $ID -key-id $keyId --key $keyPath --issuer $keyIssuer` output:
```json
{
  "logFormatVersion": 1,
  "jobId": "$ID",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "app-updater.zip",
  "uploadDate": "2023-09-15T13:06:58.269Z",
  "sha256": "...",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "app-updater.zip/app-updater.app/Contents/MacOS/app-updater",
      "message": "The signature of the binary is invalid.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087735",
      "architecture": "arm64"
    }
  ]
}
```

`codesign -vvv --deep --strict target/debug/bundle/macos/app-updater.app/Contents/MacOS/app-updater` output:
```
--prepared:.../target/debug/bundle/macos/app-updater.app/Contents/Frameworks/test.framework
--validated:.../target/debug/bundle/macos/app-updater.app/Contents/Frameworks/test.framework
target/debug/bundle/macos/app-updater.app/Contents/MacOS/app-updater: embedded framework contains modified or invalid version
In subcomponent: .../target/debug/bundle/macos/app-updater.app/Contents/Frameworks/test.framework
```

**Comment by tr3ysmith** [comment]
@lucasfernog thats bizarre, running the test now and I'm getting all passes, but when I run codesign verification, I'm getting 

```
app-updater: code has no resources but signature indicates they must be present
```

**Comment by tr3ysmith** [comment]
@lucasfernog this is my test output
```
$ cargo test --test '*' -- --ignored                                        
    Finished test [unoptimized + debuginfo] target(s) in 0.50s
     Running tests/update.rs (target/debug/deps/update-470349cf2ab872b3)

running 1 test
     Running [tauri_cli] Command `cargo  build --features custom-protocol`
   Compiling app-updater v0.1.0 (/Users/tr3ysmith/Code/tauri/core/tests/app-updater)
    Finished dev [unoptimized + debuginfo] target(s) in 3.13s
    Bundling [tauri_bundler::bundle::macos::app] app-updater.app (/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app)
    Bundling [tauri_bundler::bundle::updater_bundle] /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz (/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz)
    Finished [tauri_bundler::bundle] 1 bundle at:
        /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app
        /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz (updater)

    Finished [tauri_cli::build] 1 updater signature at:
        /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz.sig

     Running [tauri_cli] Command `cargo  build --features custom-protocol`
   Compiling app-updater v0.1.0 (/Users/tr3ysmith/Code/tauri/core/tests/app-updater)
    Finished dev [unoptimized + debuginfo] target(s) in 1.52s
        Warn [tauri_cli::build] The updater is enabled but the bundle target list does not contain `updater`, so the updater artifacts won't be generated.
    Bundling [tauri_bundler::bundle::macos::app] app-updater.app (/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app)
    Finished [tauri_bundler::bundle] 1 bundle at:
        /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app
        ```

**Comment by tr3ysmith** [comment]
I wouldn't be able to test notarization because I'm not part of your team to be able to notarize this app identifier

**Comment by lucasfernog** [comment]
> @lucasfernog this is my test output
> 
> ```
> 
> $ cargo test --test '*' -- --ignored                                        
> 
>     Finished test [unoptimized + debuginfo] target(s) in 0.50s
> 
>      Running tests/update.rs (target/debug/deps/update-470349cf2ab872b3)
> 
> 
> 
> running 1 test
> 
>      Running [tauri_cli] Command `cargo  build --features custom-protocol`
> 
>    Compiling app-updater v0.1.0 (/Users/tr3ysmith/Code/tauri/core/tests/app-updater)
> 
>     Finished dev [unoptimized + debuginfo] target(s) in 3.13s
> 
>     Bundling [tauri_bundler::bundle::macos::app] app-updater.app (/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app)
> 
>     Bundling [tauri_bundler::bundle::updater_bundle] /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz (/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz)
> 
>     Finished [tauri_bundler::bundle] 1 bundle at:
> 
>         /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app
> 
>         /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz (updater)
> 
> 
> 
>     Finished [tauri_cli::build] 1 updater signature at:
> 
>         /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app.tar.gz.sig
> 
> 
> 
>      Running [tauri_cli] Command `cargo  build --features custom-protocol`
> 
>    Compiling app-updater v0.1.0 (/Users/tr3ysmith/Code/tauri/core/tests/app-updater)
> 
>     Finished dev [unoptimized + debuginfo] target(s) in 1.52s
> 
>         Warn [tauri_cli::build] The updater is enabled but the bundle target list does not contain `updater`, so the updater artifacts won't be generated.
> 
>     Bundling [tauri_bundler::bundle::macos::app] app-updater.app (/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app)
> 
>     Finished [tauri_bundler::bundle] 1 bundle at:
> 
>         /Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app
> 
>         ```

There's no signing output here. The app id doesn't matter I think, if it does just change it to something else.

**Comment by tr3ysmith** [comment]
@lucasfernog my bad, I forgot to set environment variables so I could use my developer account to codesign/notarize, just added that, and now I'm seeing this:
```
/Users/tr3ysmith/Code/tauri/target/debug/bundle/macos/app-updater.app/Contents/Frameworks/test.framework: the main executable or Info.plist must be a regular file (no symlinks, etc.)
```

**Comment by tr3ysmith** [comment]
@lucasfernog I just ran the same codesign function directly on that `test.framework` and then also on another framework I have in another project, and its definitely a problem with that test.framework. I wonder if it got stripped somehow of its correct signature.

**Comment by lucasfernog** [comment]
I imagined it was a problem with that test framework, maybe the bundle format is wrong or something.

Btw running the "same command" isn't a good test here, we need to make sure the whole bundling process is working with codesign and notarize.

**Comment by tr3ysmith** [comment]
@lucasfernog I just created a fresh test framework and it seems to have worked, I'm going to push it up to this pull request now

**Comment by tr3ysmith** [comment]
@lucasfernog all pushed, try that

**Comment by tr3ysmith** [comment]
@lucasfernog let me know if this fixes it for you

**Comment by lucasfernog** [comment]
I'll try it as soon as I get home, thank you!

**Comment by lucasfernog** [comment]
@tr3ysmith 
```
Running [tauri_bundler::bundle::common] Command `codesign  --force -s IDENTITY -vvv target/debug/bundle/macos/app-updater.app/Contents/Frameworks/test.framework`
target/debug/bundle/macos/app-updater.app/Contents/Frameworks/test.framework: bundle format is ambiguous (could be app or framework)
```

Maybe symlinks are behaving a little weird when you push and I pull?

**Comment by tr3ysmith** [comment]
@lucasfernog if you try doing it on the framework inside the test folder, does it still do the same thing? `./core/tests/app-updater/frameworks`

**Comment by lucasfernog** [comment]
Also would be nice if you could set up commit signing, it's a requirement on our repos 😻

**Comment by tr3ysmith** [comment]
> Also would be nice if you could set up commit signing, it's a requirement on our repos 😻

Sorry! I had not realized that wasn't enabled on my end, fixed!

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
