### PR TITLE
fix(core): use `trim_start_matches` instead of `strip_prefix`

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lucasfernog** [comment]
Can you share the steps to reproduce the crash?

**Comment by amrbashir** [comment]
In a fresh `create-tauri-app` project, add `<a href="https://tauri.studio">tauri.studio</a>`

**Comment by lucasfernog** [comment]
Ahh this is a Windows thing. Unfortunate how this work lol crazy that the custom protocol is fired for external urls on windows.

**Comment by lucasfernog** [comment]
Ahh it's actually restricted to the `https://tauri` prefix in the `https://tauri.studio` URL because that's how custom protocols work on Windows lol. I'll see what I can do.

**Comment by lucasfernog** [comment]
Let's go with #4270 instead. Thanks for catching it!

**Pull request closed without merging**
