### PR TITLE
feat(bundler/nsis): sign uninstaller, closes #7348

### LINKED ISSUE #7348: [bug] windows NSIS uninstall.exe is not code signed
### Describe the bug

the uninstall.exe file created by NSIS installer is not code signed in building process, so when uninstall an app, warning of UAC is still shown.
The bundle process should also code sign the uninstall.exe file when using NSIS installer.

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC:
        - Visual Studio Community 2019
        - Visual Studio 生成工具 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.18.0
    - yarn: 3.2.4
    - npm: 8.19.2

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by amrbashir** [comment]
This is not tested yet, so I will convert to a draft

**Comment by amrbashir** [comment]
I am having a bit of a hard time trying to generate a signing certificate to test. @FabianLars if you have one, could you test this PR?

**Comment by FabianLars** [comment]
So, according to the logs all went well:
```
Finished dev [unoptimized + debuginfo] target(s) in 1m 21s
        Info Target: x64
     Signing C:\Users\Fabian-Lars\dev\_target\debug\tauri-app2.exe
     Signing C:\Users\Fabian-Lars\dev\_target\debug\tauri-app2.exe with identity "88FB696BE8176B9668F55E027D5AD83027495749"
        Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\Fabian-Lars\\dev\\_target\\debug\\tauri-app2.exe\r\r\n"
 Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
     Running candle for "main.wxs"
     Running light to produce C:\Users\Fabian-Lars\dev\_target\debug\bundle\msi\tauri-app2_0.1.0_x64_en-US.msi
     Signing C:\Users\Fabian-Lars\dev\_target\debug\bundle\msi\tauri-app2_0.1.0_x64_en-US.msi
     Signing C:\Users\Fabian-Lars\dev\_target\debug\bundle/msi/tauri-app2_0.1.0_x64_en-US.msi with identity "88FB696BE8176B9668F55E027D5AD83027495749"
        Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\Fabian-Lars\\dev\\_target\\debug\\bundle/msi/tauri-app2_0.1.0_x64_en-US.msi\r\r\n"
        Info Target: x64
     Signing C:\Users\Fabian-Lars\dev\_target\debug\tauri-app2.exe
     Signing C:\Users\Fabian-Lars\dev\_target\debug\tauri-app2.exe with identity "88FB696BE8176B9668F55E027D5AD83027495749"
        Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\Fabian-Lars\\dev\\_target\\debug\\tauri-app2.exe\r\r\n"
 Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
     Running makensis.exe to produce C:\Users\Fabian-Lars\dev\_target\debug\bundle\nsis\tauri-app2_0.1.0_x64-setup.exe
Done Adding Additional Store
Successfully signed: C:\Users\FABIAN~1\AppData\Local\Temp\nst3D2C.tmp
     Signing C:\Users\Fabian-Lars\dev\_target\debug\bundle\nsis\tauri-app2_0.1.0_x64-setup.exe
     Signing C:\Users\Fabian-Lars\dev\_target\debug\bundle/nsis/tauri-app2_0.1.0_x64-setup.exe with identity "88FB696BE8176B9668F55E027D5AD83027495749"
        Info "Done Adding Additional Store\r\nSuccessfully signed: C:\\Users\\Fabian-Lars\\dev\\_target\\debug\\bundle/nsis/tauri-app2_0.1.0_x64-setup.exe\r\r\n"
    Finished 2 bundles at:
        C:\Users\Fabian-Lars\dev\_target\debug\bundle\msi\tauri-app2_0.1.0_x64_en-US.msi
        C:\Users\Fabian-Lars\dev\_target\debug\bundle\nsis\tauri-app2_0.1.0_x64-setup.exe
```

Gonna try and see if i can confirm that somehow...

**Comment by FabianLars** [comment]
Well, at least according to the "digital signatures" (translated from german) tab in the file properties of the uninstall.exe it correctly lists the cert like it does on the installer & app. 🥳

**Comment by jetli** [comment]
I tested this pr too, confirm that the uninstall.exe is signed correctly, thanks! and with the few latest fixes, NSIS works great now!

**Comment by amrbashir** [comment]
thanks for testing, I marked this as ready for review now

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
