### PR TITLE
refactor(core): split endpoint API matching into modules

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by nklayman** [comment]
This mostly works for me, but a few api features don't work. However, I don't think they were working before either so it's probably not related to this PR.

**Comment by lucasfernog** [comment]
> This mostly works for me, but a few api features don't work. However, I don't think they were working before either so it's probably not related to this PR.

Which APIs aren't working?

**Comment by nklayman** [comment]
Like half of the api examples, I can give you a full list later if you want.

**Comment by lucasfernog** [comment]
Did you rebuild the API module? :)

**Comment by nklayman** [comment]
Yep, still fails on the following:
- Read file: `ReferenceError: Can't find variable: pathInput`
- HTTP Request: `TypeError: _e.request is not a function. (In '_e.request(t)', '_e.request' is undefined)`
- Open URL: `TypeError: J.open is not a function. (In 'J.open(i)', 'J.open' is undefined)`
- Send event to Rust: Console doesn't display anything, no way to tell that it worked

Seems like all these errors are on the JS side. These errors come up when I first run the app as well:

```
[Error] Error: you are trying to use the global Tauri script but the @tauri-apps/api package wasn't compiled; run `yarn build` first
	Global Code
[Error] TypeError: undefined is not an object (evaluating 'window.__TAURI__.windows = ["main"].map(function (label) { return { label: label } })')
	Global Code
```

I've built the api with `yarn build`, and the `dist` folder is populated with a bunch of scripts. Is there something else I'm missing?

**Comment by lucasfernog** [comment]
I'll investigate this, seems like it's really an issue. Thanks for checking it Noah!

**Pull request merged**
