### PR TITLE
feat(tauri): add frameless window

### LINKED ISSUE #158: Frameless window
**Describe the solution you'd like**
An option to spawn a window without a frame or "chrome" border/title bar/window controls (min/max/restore/close), requiring the app to supply it's own window controls

**Additional context**

borderlessresizablewithchild

### PR DESCRIPTION
**Pull request by DrSensor**
fix #158

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [ ] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
`webview-rs` v0.6.1 now support frameless/borderless window

### CODE REVIEW

**Comment by jbolda** [comment]
Are we waiting to merge this for a specific reason?

**Comment by nothingismagick** [comment]
We are waiting for this until our move to `zserge` is complete. Merging it now *might* introduce a dependency on boscop.

**Comment by AlveLarsson** [comment]
How does this handle Draggable regions and resizing of the window or at all?
it's super close to allow custom CSS title bars :P

**Comment by lucasfernog** [comment]
I'm closing this PR since we'll probably take a different approach when [wry](https://github.com/tauri-apps/wry) lands and the upstream webview library doesn't support it. Thank you for your contribution though @DrSensor !

**Comment by Blakeinstein** [comment]
> How does this handle Draggable regions and resizing of the window or at all?
> it's super close to allow custom CSS title bars :P
> 
> like here:
> https://www.electronjs.org/docs/api/frameless-window#draggable-region
> 
> (I presume this is outside the scope of this PR, just checking)

I handled resizing of frameless windows on windows version of boscop/webview. Its more of a hack and I wouldn't recommend using it but basically it tries to add a 5px gap on the edges for the frame where events are passed to the window handler for resizing... The 5px gap is necessary since webview would consume mouse events otherwise. 

My usecase was a windows only application and hence I did not look into mac/linux.

**Pull request closed without merging**
