### PR TITLE
feat(bundler/windows): Update wix to fix vulnerabilities and add arm support

### PR DESCRIPTION
**Pull request by FabianLars**
(careful, v1 branch!)

I won't be able to actually test this until Sunday but opening this for a community member to test (and for whoever else that wants to of course)

### CODE REVIEW

**Review by lucasfernog — DISMISSED** [review]
tested on UTM, works

**Comment by lucasfernog** [comment]
is this one ready @FabianLars ?

**Comment by FabianLars** [comment]
Change of plans and I wasn't home yet since I opened it. If you say it's working then I think it's good (check the change files and remove the bump one if you're not gonna release it quickly, we just wanted to match minors again).

Also not the biggest fan of the new folder but I guess that's the only way to make sure it gets the new one. Maybe we should use this versioning in general and add a tauri clean command idk

**Comment by FabianLars** [comment]
With 9706(?) merged the bump changefile is useless, please remove it before merge (Idk if im dumb but deleting files is not working in the app for me)

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
