### PR TITLE
fix: improve checking for Rez (fix #994)

### LINKED ISSUE #994: tauri fails to find Rez when Xcode (the app, not the command line tools) is not installed.
**Describe the bug**
When Xcode Command Line Tools are installed, Rez is located at /Library/Developer/CommandLineTools/usr/bin/Rez. Tauri looks in /Applications/Xcode.app/Contents/Developer/Tools/Rez, which doesn't exist if the Xcode app is not installed.

**To Reproduce**
1. Uninstall Xcode if it is installed on your system
2. Run `xcode-select --install` to install Xcode Command Line Tools
3. Run `tauri build --verbose`
4. Tauri will display the following error when attempting to find Rez:

```
adding EULA resources
Failed to find Rez at "/Applications/Xcode.app/Contents/Developer/Tools/Rez"!

Usage: dmg-license.py <dmgFile> <licenseFile> [OPTIONS]
  This program adds a software license agreement to a DMG file.
  It requires Xcode and either a plain ascii text <licenseFile>
  or a <licenseFile.rtf> with the RTF contents.

  See --help for more details.

error: Shell Scripting Error:`error running bundle_dmg.sh`
```

**Expected behavior**
Tauri checks if Xcode is installed, and if not, looks for the Command Line Tools. If neither are found a human-readable error is thrown telling the user to run `xcode-select --install`

**Screenshots**
image

**Platform and Versions (please complete the following information):**

```
Operating System - Darwin(19.6.0) - darwin/x64

Node.js environment
  Node.js - 14.8.0
  tauri.js - 0.12.0

Rust environment
  rustc - 1.45.2
  cargo - 1.45.1
  tauri-bundler - 0.9.2

Global packages
  NPM - 6.14.7
  yarn - 1.22.4
```

**Additional context**
As a workaround I'm just installing Xcode, although it would be nice if this was patched so I could save some space on my hard drive 😅 

Thanks so much for your tireless work on this project! It's been a surprisingly smooth experience getting up and running with Tauri, even with limited Rust knowledge ❤️

### PR DESCRIPTION
**Pull request by caass**
Check for Rez in Xcode.app and in command line tools, and error if neither is installed.

**What kind of change does this PR introduce?** (check at least one)
Fixes #994 

- [x] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
I haven't tested this at all, this is just my naïve attempt to fix this behavior. Please let me know what I've done wrong and I'll correct it. ❤️

### CODE REVIEW

**Comment by caass** [comment]
There's no pretty error message telling folks to install command line tools for xcode, however I'm pretty sure that the error stack will make it pretty obvious with a single google search what the problem is. There's about a million Medium articles explaining how to run `xcode-select --install`.

**Comment by caass** [comment]
Ok so CI failed, but I'm not sure it was related to my change. Relevant output:
```sh
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-x64.tar.gz
ERR! sharp connect ETIMEDOUT 52.216.160.155:443
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
```
I think this is just a network timeout. I've seen some stuff about this being an issue, I wonder if triggering a re-run will fix it.

**Comment by jbolda** [comment]
Could you do something like `${xcode-select --print-path || echo "Can't find Rez at $1, try installing via `xcode-select --install`"}`? You might need to check my bash typing from my phone.

**Comment by jbolda** [comment]
Actually, you could add to the error message here: https://github.com/tauri-apps/tauri/blob/91dd7af79efab3d18abc7f29107a87618a7b2b1f/cli/tauri-bundler/src/bundle/templates/dmg/dmg-license.py#L158

**Review by jbolda — APPROVED** [review]
Thanks again for your help with this!

**Pull request merged**
