### PR TITLE
feat: implement `Default` for `Menu`, closes #2398

### LINKED ISSUE #2398: feat: add a default menu for tauri apps
On macOS, it's pretty much standard for every app to have a menu. Not having one looks very unusual, and basic shortcuts like copy/paste don't work (https://github.com/tauri-apps/tauri/issues/2397). This could result in future issues being created, and unexpected surprises for people who develop on Windows/Linux.

To prevent that, I think it would make sense to have a default macOS menu.

Suggestion for what the default menu should be, and API for it:
```rust
impl Menu {
  pub fn default() -> Menu {
    Menu::new()
      .add_default_submenu(Submenu::App)
      .add_default_submenu(Submenu::File)
      .add_default_submenu(Submenu::Edit)
      .add_default_submenu(Submenu::View)
      .add_default_submenu(Submenu::Window)
      .add_default_submenu(Submenu::Help("https://tauri.studio"))
  }

  pub fn add_default_submenu(&mut self, submenu: Submenu) {
    match submenu {
      Submenu::App => {
        #[cfg(target_os = "macos")]
        self.add_submenu(Submenu::new(
          app_name,
          Menu::new()
            .add_native_item(MenuItem::About(app_name))
            .add_native_item(MenuItem::Separator)
            .add_native_item(MenuItem::Services)
            .add_native_item(MenuItem::Separator)
            .add_native_item(MenuItem::Hide)
            .add_native_item(MenuItem::HideOthers)
            .add_native_item(MenuItem::ShowAll)
            .add_native_item(MenuItem::Separator)
            .add_native_item(MenuItem::Quit),
        ));
      }

      Submenu::File => {
        self.add_submenu(Submenu::new(
          "File",
          if cfg!(target_os == "macos") {
            Menu::new().add_native_item(MenuItem::CloseWindow)
          } else {
            Menu::new().add_native_item(MenuItem::Quit)
          },
        ));
      }

      Submenu::Edit => {
        self.add_submenu(Submenu::new("Edit", {
          let mut menu = Menu::new();
          menu = menu.add_native_item(MenuItem::Undo);
          menu = menu.add_native_item(MenuItem::Redo);
          menu = menu.add_native_item(MenuItem::Separator);
          menu = menu.add_native_item(MenuItem::Cut);
          menu = menu.add_native_item(MenuItem::Copy);
          menu = menu.add_native_item(MenuItem::Paste);
          #[cfg(not(target_os = "macos"))]
          {
            menu = menu.add_native_item(MenuItem::Separator);
          }
          menu = menu.add_native_item(MenuItem::SelectAll);
          menu
        }));
      }

      Submenu::View => {
        self.add_submenu(Submenu::new(
          "View",
          Menu::new().add_native_item(MenuItem::EnterFullScreen),
        ));
      }

      Submenu::Window => {
        self.add_submenu(Submenu::new("Window", {
          let menu = Menu::new()
            .add_native_item(MenuItem::Minimize)
            .add_native_item(MenuItem::Zoom);
          if cfg!(target_os == "macos") {
            menu.add_native_item(MenuItem::Separator);
            // not yet supported:
            menu.add_native_item(MenuItem::BringAllToFront);
            // not yet supported (window selector):
            menu.add_native_item(MenuItem::Window);
          } else {
            menu.add_native_item(MenuItem::CloseWindow);
          }
        }));
      }

      Submenu::Help(url) => {
        self.add_submenu(Submenu::new(
          "Help",
          Menu::new()
            // should open url when clicked:
            .add_item(MenuItem::Url("Learn More", url)),
        ))
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [x] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lorenzolewis** [comment]
It looks like app_name is only used for macOS. Curious if this could be optional and we provide a default name from the config if not specified? One less thing to get it up and running.

What were your thoughts on having this in the default template when creating a new app?

And then lastly just a nit-pick on the function name, any reason to have it as `new_default` instead of just `default`?

**Comment by amrbashir** [comment]
> It looks like app_name is only used for macOS. Curious if this could be optional and we provide a default name from the config if not specified? One less thing to get it up and running.

The app name is needed for the `About` menu item. There is no way else to get it. It is a minor inconvenience if you ask me.

> What were your thoughts on having this in the default template when creating a new app?

Sure, not the current CTA though, but once https://github.com/tauri-apps/create-tauri-app/pull/61 lands.

> And then lastly just a nit-pick on the function name, any reason to have it as `new_default` instead of just `default`?

Well, `Menu` already implements `Default` trait so `default` is taken and I didn't want to cause collisions. if I name it `default` instead of `new_default`, we will have to remove `Default` trait derive and that will be a small breaking change.

**Comment by lorenzolewis** [comment]
Ah, didn't think of the conflict with `Default`. What about something like `add_default` or `build_default`? `new_default` reads a bit weird, but that could just be me.

And points taken for the other two

**Comment by amrbashir** [comment]
Since it takes the app name as an argument, it should be fine to just name it `default`

**Comment by martpie** [comment]
Thank you so much for working on that! That's such a nice improvement!

**Pull request merged**
