### PR TITLE
feat(nsis): implement `passive` mode, closes #6955

### LINKED ISSUE #6955: [bug] NSIS auto updater passive mode
### Describe the bug

The current NSIS updater requires user interaction to install the update., even with the passive option in the configuration. 
`"windows": {
        "installMode": "passive"
      }`

### Reproduction

- make nsis build
- make update
- open app and get update notification
- install update
- update not passive

### Expected behavior

update is passive with a progress bar like the msi updater

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64        
    ✔ WebView2: 113.0.1774.35
    ✔ MSVC: 
        - Visual Studio Build Tools 2022
        - Visual Studio Build Tools 2019
    ✔ rustc: 1.67.1 (d5a82bbd2 2023-02-07)
    ✔ Cargo: 1.67.1 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - pnpm: 8.3.1
    - yarn: 1.22.10
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' data: asset: https://asset.localhost; style-src 'self' 'unsafe-inline'; font-src 'self' data:
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amrbashir**
### What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by FabianLars** [comment]
It doesn't seem to work when used in the updater, it will still show the default dialog. Using the flags in the console the passive mode (which looks nice btw) does work.

I didn't triage it yet, just wanted to give a headsup so we don't merge it too eagerly :)

**Comment by amrbashir** [comment]
thanks Fabian, I will test again tomorrow.

**Comment by FabianLars** [comment]
Found it: https://github.com/tauri-apps/tauri/blob/abdd25616128841d2c0eee4ece78c377dd0e3fd1/core/tauri/src/updater/core.rs#L739-L743

**Comment by amrbashir** [comment]
Nice catch 💯 , I checked that code twice to make sure the args are passed in, but didn't pay attention to the `if` check.

**Review by FabianLars — DISMISSED** [review]
Sorry for the delay, i really thought i approved already...

On a side node i just noticed, when the update is installed, the nsis dialog doesn't get focus and will be stuck behind other windows. -> This is the same for passive and basicUi modes. It's alright-ish for the passive mode but more problematic when user action is required (basicUi). Anyway, that's prob something for a different PR just wanted to raise awareness.

**Comment by lucasfernog** [comment]
@FabianLars can you open an issue so we don't foget about this issue?

**Review by lucasfernog — DISMISSED** [review]
Works well. I know sometimes it's complicated to do it, but ideally each feature would have its own PR. I promise I'll try to be faster reviewing it :joy:

**Comment by amrbashir** [comment]
It is my bad, I just kept finding bugs as I was implementing the passive mode and was fixing them along the way.

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
