### PR TITLE
@tauri-apps/api  - Feature. Declaration merging.

### PR DESCRIPTION
**Pull request by veatla**
### What kind of change does this PR introduce?
- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

#### I have added global interface called `TauriInvokeTypes `. 
btw I tried to create interface inside of `namespace` but I didn't figured out. Eslint throws errors :/

# How it work?
You can declare interface in global scope and set invoke types that will throw error if typeof assignable value or argument doesn't matches.

For example:
```ts
declare global {
  export interface TauriInvokeTypes {
    login: (args: { password: string; username: string }) => Promise<boolean>;
  }
}

```

Screenshot 12-02-2023 04 08 21

### CODE REVIEW

**Comment by amrbashir** [comment]
Honestly, I don't think this is something we should add directly in the package to keep the types simple and reduce maintenance burden. Also the user can create a wrapper function around `invoke` and change the types as your proposed. but I will let @lucasfernog to decide

**Comment by veatla** [comment]
Ok

**Comment by lucasfernog** [comment]
I think this adds too much overhead. We're thinking about moving to tauri-bindgen in the future instead, and maybe implement [tauri-specta](https://github.com/oscartbeaumont/tauri-specta) in the meantime, we just didn't get to it yet.

**Comment by veatla** [comment]
Okay

**Pull request closed without merging**
