### PR TITLE
fix(core): add hash symbol in uri parse, closes #1943

### LINKED ISSUE #1943: iframe with fragment in src don't render
**Describe the bug**
The problem is when iframe src includes a URI fragment, like `#something`, it won't load when you try to load it from disk.

**To Reproduce**
Minimal reproducible example placed here:
https://github.com/olegshilov/tauri-testing/tree/iframe-issue
Steps to reproduce:
- clone
- install dependencies
- run `yarn start` or `yarn build`

**Expected behavior**
Every iframe with fragments in URL must be rendered correctly 

**Screenshots**
image

**Platform and Versions (please complete the following information):**
```shell
❯ yarn tauri info
 app:spawn Running "/Users/olegshilov/Documents/tauri-testing/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.2-71cdee115b/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 15.7.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - Not installed

Global packages
  npm - 7.5.3
  yarn - 3.0.0-rc.2.git.20210514.hash-4d53b9eb

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/.yarn
/app
/src-tauri
/.git

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
distDir - ../app
devPath - ../app

```

### PR DESCRIPTION
**Pull request by olegshilov**
**What kind of change does this PR introduce?** (check at least one)
Described here: https://github.com/tauri-apps/tauri/issues/1943

- [x] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by amrbashir** [comment]
Since this PR is touching the `#`, I am a little concerned about hashed routes, will this affect how they behave or not (sry, can't test it atm)? 

Ideally two things should be working:
1. Routing within a SPA by calling the hashed router respective methods, for example: vue-router's `router.go(1)` or  `router.push('route-name')`.

2. Navigating to a hashed route like `tauri://custom-protocol/#/nested/route` as if you type it in the address bar of a normal browser. maybe @lucasfernog can have more insight on how we might test this in tauri context

**Comment by lucasfernog** [comment]
> Since this PR is touching the `#`, I am a little concerned about hashed routes, will this affect how they behave or not (sry, can't test it atm)?
> 
> Ideally two things should be working:
> 
> 1. Routing within a SPA by calling the hashed router respective methods, for example: vue-router's `router.go(1)` or  `router.push('route-name')`.
> 2. Navigating to a hashed route like `tauri://custom-protocol/#/nested/route` as if you type it in the address bar of a normal browser. maybe @lucasfernog can have more insight on how we might test this in tauri context

Hash route does not trigger the custom protocol, it is handled by the router framework. Since the hash portion is just an anchor, it doesn't trigger a new page load.

**Comment by lucasfernog** [comment]
I'll test this anyway.

**Comment by lucasfernog** [comment]
Works like a charm, tested with a Vue router hash mode app (https://github.com/mayank091193/quasar-scrum) and it didn't affect it since the hash URLs doesn't even hit the custom protocol.

**Review by lucasfernog — APPROVED** [review]

**Comment by amrbashir** [comment]
My bad then, I thought directly navigating to a hashed route would still try to go through custom protocol. 

Thanks for the PR @olegshilov

**Pull request merged**
