### PR TITLE
Extend context.rs to dynamically find the OUT_DIR for certain assets

### PR DESCRIPTION
**Pull request by sinistersnare**
Hello, my team is moving to Bazel, and we can not use tauri-cli or any of your custom cargo-based tooling. We would like to contribute our changes to you all, so you can better support Bazel. 

These changes should be non-breaking, as it just recalculates the OUT_DIR at build.rs-time and compile-time separately. So it should not affect Cargo builds.

I think that TODO, if this is going to be fully generalized we need to add this functionality to some other parts of at least this file.

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lucasfernog** [comment]
@sinistersnare is this PR ready or do you want to change some other OUT_DIR usage?

**Comment by sinistersnare** [comment]
I think its fine for now. It can be further extended as needed using the code here as a template for future contributors.

**Comment by lucasfernog** [comment]
By the way @sinistersnare this PR is targeting v2. So if you want this to be part of v1.5, it needs to target the `1.x` branch instead.

**Comment by sinistersnare** [comment]
Ah thanks for the check on that. I rebased on 1.x

**Comment by sinistersnare** [comment]
I extended the PR to include another case useful to my project. Overall, this kind of stuff is really useful for non-Cargo users, and the codegen crate would be wise to generalize from any build tool.

**Review by lucasfernog — DISMISSED** [review]

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
