### PR TITLE
Command support for specified character encoding, closes #4644

### LINKED ISSUE #4644: [bug] @tauri-apps/api/shell exists utf8 parsing error on window
### Describe the bug

When I use the simplified Chinese version of window, the console will return GBK encoded data and an `invalid utf-8 sequence of 1 bytes from index 0` error will occur. I think all non-English versions of window may have that problem.

### Reproduction

1. `import { Command } from '@tauri-apps/api/shell';`
2. `new Command('cmd', ['/C','echo 你好，世界']).execute();`

After that, you will get the error.

### Expected behavior

No string parsing errors.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.49
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0 (outdated, latest: 1.0.3)
  › @tauri-apps/api [NPM]: 1.0.1 (outdated, latest: 1.0.2)
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ build
  ├─ node_modules
  ├─ public
  ├─ rumqtt
  ├─ scripts
  ├─ src
  └─ src-tauri
```

### Stack trace

_No response_

### Additional context

In fact, I think the error comes from [this line](https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/process/command.rs#L395)，and I'd be happy to submit a PR in a few days to allow the user to specify the encoding (default utf-8) if you agree.

### PR DESCRIPTION
**Pull request by horochx**
### What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by lucasfernog** [comment]
@horochx I assume this also fixes #2673 right? I'll test it tonight.

**Comment by lucasfernog** [comment]
Which encoding did you use for simplified chinese? Tried a couple ones but it wasn't perfect :D

**Comment by lucasfernog** [comment]
Ahh just found it in the issue, nvm.

**Comment by horochx** [comment]
> Which encoding did you use for simplified chinese? Tried a couple ones but it wasn't perfect :D

When I use `gbk`, it works fine~

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
