### PR TITLE
Don't run the update-docs workflow for unimportant changes

### PR DESCRIPTION
**Pull request by thadguidry**
- Added ignored (!) paths that we don't want the update-docs workflow to even start and instead skip it entirely.  See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns-1
- Probably might be other folders or files that could be ignored to skip the update-docs workflow (I don't know what they might be however)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe: CI/CD

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [X] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by Laegel** [comment]
Thanks for the PR @thadguidry 
I'm not sure we would make a release that doesn't imply any modification on the docs but I guess in this case it's "better safe than sorry", right?
What do you think @lucasfernog ?

**Comment by thadguidry** [comment]
Ah then we probably want context at 2 event levels. A push or a release? And we could deal with each uniquely with their own criteria.  On this PR it touches the docs ci/cd workflow and not a step within it.

There are options at different levels.

What do you think?

**Comment by Laegel** [comment]
Why would we trigger the workflow on a push event?

**Comment by thadguidry** [comment]
@Laegel Thanks for explaining more about the Docs updating on Discord!  So now that I understand more, we don't need this and can close this.

**Pull request closed without merging**
