### PR TITLE
Update ico package

### PR DESCRIPTION
**Pull request by VirxEC**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

`ico` version `0.1` requires `png` version `0.11`, and is the only package in the Tauri project to require this old version. Recently, an update was pushed to `ico` which bumped the version to `0.2` and updated `png` to the latest version, `0.17` (the same version Tauri uses elsewhere.)

This change was 100% backward compatible with Tauri's usage of the `ico` package and no code in Tauri needs to be changed, just a version bump where the dependency is listed. I've confirmed by looking in the generated `Cargo.lock` that there is now only one version of `png` that needs to be built, version `0.17`.

I'm not sure if there's a schedule for updating dependencies but this change is trivial and also won't be automatic just by running `cargo update` so I figured I'd open this PR and see what happens haha

### CODE REVIEW

**Comment by FabianLars** [comment]
We use renovate to update dependencies but it only runs Wednesdays and `ico` was released just 2 hours ago so it wasn't updated the last time it ran.

**Comment by VirxEC** [comment]
@FabianLars should I close this pr then?

**Comment by FabianLars** [comment]
leave it open for now, let's see what Lucas thinks

**Comment by VirxEC** [comment]
Fixed conflicts because the `ico` version in `tauri-codegen` was updated but not the optional dep in the main `tauri` package

**Comment by lucasfernog** [comment]
We usually don't include dependency bumps in the changelog (too many damn dependencies) but we'll need to publish a patch for 1.2 soon anyway :)

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
