### PR TITLE
feat(bundler) add option to bundle external binaries

### PR DESCRIPTION
**Pull request by lucasfernog**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lucasfernog** [comment]
@tensor-programming do you know if I can spawn a command without opening the console on Windows?

**Comment by nothingismagick** [comment]
WOW! I’ll test this tomorrow

**Comment by tensor-programming** [comment]
> @tensor-programming do you know if I can spawn a command without opening the console on Windows?

You should be able to do that.  Try using the cfg macro that we added to the each of the examples.

**Comment by lucasfernog** [comment]
I think i'm alright, the biggest issue here is that I had to duplicate the `platform.rs` code. Should I use `tauri-api` as a dependency of the bundler?

**Comment by tensor-programming** [comment]
> I think i'm alright, the biggest issue here is that I had to duplicate the `platform.rs` code. Should I use `tauri-api` as a dependency of the bundler?

No I don't think we want to have everything be a dep of each other. It would increase the compile time significantly. We can however take those common functions and split them off into a utils crate.

**Comment by nothingismagick** [comment]
LGTM

**Comment by Tom-sudo-web** [comment]
How to bundle external binaries and how to call the binaries I bundled?

**Pull request merged**
