### PR TITLE
Fix typos referring to CLI args in init command

### PR DESCRIPTION
**Pull request by zakpatterson**
The devPath config variable is set to a non-existent command line arg
`argv.p`, it should be `argv.P`

So if the devPath is set via a command line argument, it defaults
to the default value:

```
/home/projects/example2
⟩ yarn tauri init -P http://THISDOESNOTHING
yarn run v1.22.4
$ /home/projects/example2/node_modules/.bin/tauri init -P http://THISDOESNOTHING
[tauri]: running init
? What is your app name? example2
? What should the window title be? Tauri App
? Where are your web assets (HTML/CSS/JS) located, relative to the "<current dir>/src-tauri" folder that will be created? ../dist
 dependency:manager Installing missing dependencies... +0ms
 dependency:cargo-commands "tauri-bundler" is already installed +18ms
 app:spawn [sync] Running "cargo generate-lockfile" +2ms

    Updating crates.io index
 dependency:crates "tauri" is already installed +941ms
 dependency:npm-packages "tauri" is already installed +1s
Done in 6.35s.

/home/projects/example2
⟩ cat ./src-tauri/tauri.conf.json | grep THISDOESNOTHING

/home/projects/example2
```

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] New Binding Issue #___
- [ ] Code style update
- [ ] Refactor
- [X] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes. Issue #___
- [X] No

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number) -- **N/A**
- [X] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by jbolda** [comment]
Does this also apply to window title as well?

**Review by jbolda — CHANGES_REQUESTED** [review]
Looks good to me. Would you please add a change file as well. Instructions are linked in the check box item requesting one.

**Comment by zakpatterson** [comment]
> Looks good to me. Would you please add a change file as well. Instructions are linked in the check box item requesting one.

The change file project is pretty neat. I didn't think this required a semver version update, but what wouldn't?

**Comment by jbolda** [comment]
It feels like functionality everything gets a change file unless it is internal workflow kind of changes or doc updates.

**Review by jbolda — APPROVED** [review]

**Pull request merged**
