### PR TITLE
refactor(bundler): switch to notarytool, closes #4300

### LINKED ISSUE #4300: (bundler): Switch to notarytool for notarization before Fall 2023
For reference: https://developer.apple.com/videos/play/wwdc2022/10109/

Relevant file: https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/macos/sign.rs

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by amrbashir — COMMENTED** [review]
releasing this as a minor release might break some users CI, should it be added behind a flag and the default would warn users that it is to be discontinued soon and they should migrate?

**Comment by lucasfernog** [comment]
It will break anyway in a couple months...

**Comment by amrbashir** [comment]
true but we could have a soft migration at the moment instead of breaking their CI early on.

**Comment by FabianLars** [comment]
tbh i feel like it's too late for that now, especially with our slow-ish release cycle

**Comment by lucasfernog** [comment]
We could also look for the API key file on the known paths Apple used to look for it...

**Review by amrbashir — APPROVED** [review]

**Pull request merged**
