### PR TITLE
refactor(core): custom protocol on Windows now uses the http scheme

### PR DESCRIPTION
**Pull request by lucasfernog**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by amr-crabnebula — APPROVED** [review]

**Review by amrbashir — APPROVED** [review]

**Comment by FabianLars** [comment]
Am i right to assume that we don't want this to be configurable? I'm asking because i'd lean towards closing https://github.com/tauri-apps/tauri/pull/7645 if that's the case.

**Comment by lucasfernog** [comment]
I think for v1 it's valuable to add a config option for it (since it's a popular issue). For v2 I don't really want to bloat the code with this check, though it could be added if the community / security team feels it's a nice addition (though it sucks that it only helps windows/android).

**Comment by FabianLars** [comment]
Yeah, it's just that adding a new but deprecated API has a bit of a weird vibe but alright, at least the PR wasn't wasted time then :D

And in v2 I think a better request API (basically on_navigation but for everything) would solve the problem better than the https scheme since it would be cross platform.

**Comment by percy507** [comment]
Hi @lucasfernog,

Why Windows use `http` scheme now instead of `https`? I mean no harm. Just curious.

**Comment by amrbashir** [comment]
allows for connecting to insecure protocols like `ws` instead of `wss` which has been the main reason for this change

**Pull request merged**
