### PR TITLE
fix(core): Use productName for FileDescription

### LINKED ISSUE #10890: [feat] Add windows settings description text
### Describe the problem

The `tauri.config.json.bundle.shortDescription` currently corresponds to the text framed with the red rectangle on the attached screenshot.

tauri-bundle-short-description

I'd like an ability to set a text framed with the green rectangle.

This settings are available in "Taskbar Settings" under "Select the icons displayed on the taskbar" link. I'm not 100% sure about the exact wording as my system is not in english.

### Describe the solution you'd like

Breaking:

1. `tauri.config.json.bundle.shortDescription` becomes the text on the bottom
2. Add `tauri.config.json.bundle.appName` that becomes text on the top

Non-breaking:

Add a new key to `tauri.config.json.bundle` that corresponds to the text on the bottom 

### Alternatives considered

_No response_

### Additional context

Windows 10, idk if Windows 11

### LINKED ISSUE #10968: [bug][File Association] "Open with" displays the app description instead of the app name on Windows
### Describe the bug

On Windows, when setting up File Association (NSIS + .msi), the description is used in the "Open With" dialog instead of the product/app name. (should be "Museeks", not "A clean, simple and cross-platform music player" ).

unnamed

(sorry, not possible to take screenshot of context menus in Windows 11, weirdly)

On macOS, works as expected:

unnamed

### Reproduction

Not a minimal reproduction, sorry:

```
git clone https://github.com/martpie/museeks.git
cd museeks
git checkout file-associations-tauri
bun install
bun tauri install
# then install the app from `src-tauri\target\release\bundle`
```

### Expected behavior

It should be using the app name, and not the app description.

### Full `tauri info` output

```text
$ tauri info

[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 128.0.2739.67
    ✔ MSVC:
        - Visual Studio Build Tools 2019
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 22.8.0
    - pnpm: 9.8.0
    - yarn: 1.22.22
    - npm: 10.8.1
    - bun: 1.1.26

[-] Packages
    - tauri 🦀: 2.0.0-rc.10
    - tauri-build 🦀: 2.0.0-rc.9
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.12

[-] Plugins
    - tauri-plugin-single-instance 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-window-state 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-window-state : not installed!
    - tauri-plugin-fs 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-os 🦀: 2.0.0-rc.1
    - @tauri-apps/plugin-os : 2.0.0-rc.1
    - tauri-plugin-notification 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-notification : 2.0.0-rc.1
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1
    - tauri-plugin-dialog 🦀: 2.0.0-rc.5
    - @tauri-apps/plugin-dialog : 2.0.0-rc.1
    - tauri-plugin-log 🦀: 2.0.0-rc.2
    - @tauri-apps/plugin-log : 2.0.0-rc.1

[-] App
    - build-type: bundle
    - CSP: default-src 'none'; img-src 'self' data:; media-src 'self' asset: https://asset.localhost http://asset.localhost; child-src 'self'; object-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src ipc: http://ipc.localhost 'self' https://api.github.com; font-src 'self' data:
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```
```


### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FabianLars**
fixes #10968
fixes #10890

There's also a VersionInfo FileDescription in the nsis installer template but i didn't see this being applied/used anywhere so i didn't touch it yet. Maybe windows 7 shows it still? From what i saw on StackOverflow, VersionInfo isn't really used since Vista but idk.

### CODE REVIEW

**Comment by amrbashir** [comment]
Lets change the NSIS as well, for consistency

**Comment by FabianLars** [comment]
tbh was almost considering to remove it. I can't even see the value it sets with things like exiftool. Any idea where it's used/Where i can see it? Even started my win7 vm for this.

**Comment by amrbashir** [comment]
It is not really used in anything, it can only be visible in the `Details` tab when checking the properties of the installer executable. I am fine with removing as well, but I think we should just update it to use productName

**Comment by FabianLars** [comment]
ffs, i didn't use the damn local cli/bundler when testing this, holy shit.

**Review by amrbashir — APPROVED** [review]

**Comment by martpie** [comment]
Thank you for the fix!

**Pull request merged**
