### PR TITLE
use cargo workspace package table

### PR DESCRIPTION
**Pull request by chippers**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information
We can use the [Cargo Workspace Package Table](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) in order to set the same values that are used for many `[package]` keys in most packages. I think we could also use this for tooling and examples, but we need to figure out how we want to structure the workspace before that.

### CODE REVIEW

**Comment by chippers** [comment]
@FabianLars will this also run into the problem you described in https://github.com/tauri-apps/tauri/pull/6842#issuecomment-1532789897?

**Comment by FabianLars** [comment]
Yeah, covector will convert the syntax to
```toml
  [package.authors]
  workspace = true
```
and will remove the comment.

Edit: covector seems to rewrite the whole file and not just the parts it actually has to modify.

**Comment by lucasfernog** [comment]
I actually had to use the `dep = { workspace = true }` syntax instead of `dep.workspace = true` to not get that ugly format from covector.

**Comment by chippers** [comment]
Unfortunate, is this a problem with covector or a dependency of it? Is this tracked somewhere?

**Comment by lucasfernog** [comment]
It's a problem with https://github.com/tauri-apps/tauri-toml @chippers

**Comment by lucasfernog** [comment]
I'll see if updating the fork fixes it.
EDIT: nope, no easy way to adjust it :(

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
